// Allgemeinwissen für den Ranglisten-Modus: bewusst quer durch alles,
// abseits der Themen aus dem freien Spiel.
module.exports = (E, M, Y) => {
  E('Wie viele Knochen hat ein erwachsener Mensch?', 206, 'Knochen', 'Allgemeinwissen');
  E('Wie viele Zähne hat ein erwachsener Mensch mit allen Weisheitszähnen?', 32, 'Zähne', 'Allgemeinwissen');
  E('Wie viele Liter Blut hat ein erwachsener Mensch ungefähr?', 5, 'Liter', 'Allgemeinwissen');
  E('Wie oft schlägt ein ruhendes Herz pro Minute im Schnitt?', 70, 'Schläge', 'Allgemeinwissen');
  E('Wie viele Grad hat die Summe der Innenwinkel eines Dreiecks?', 180, 'Grad', 'Allgemeinwissen');
  E('Wie viele Felder hat ein Schachbrett?', 64, 'Felder', 'Allgemeinwissen');
  E('Wie viele Karten hat ein Skatblatt?', 32, 'Karten', 'Allgemeinwissen');
  E('Wie viele Augen hat ein Würfel insgesamt?', 21, 'Augen', 'Allgemeinwissen');
  E('Wie viele Tasten hat ein Standard-Klavier?', 88, 'Tasten', 'Allgemeinwissen');
  E('Wie viele Sekunden hat ein Tag?', 86400, 'Sekunden', 'Allgemeinwissen');
  E('Bei wie viel Grad Celsius siedet Wasser auf Meereshöhe?', 100, '°C', 'Allgemeinwissen');
  E('Wie viele Buchstaben hat das deutsche Alphabet ohne Umlaute?', 26, 'Buchstaben', 'Allgemeinwissen');
  E('Wie viele Bundesländer hat Deutschland?', 16, 'Länder', 'Allgemeinwissen');
  E('Wie viele Mitgliedsstaaten hat die Europäische Union (Stand 2025)?', 27, 'Staaten', 'Allgemeinwissen');
  E('Wie viele Beine hat eine Spinne?', 8, 'Beine', 'Allgemeinwissen');
  E('Wie viele Herzen hat ein Oktopus?', 3, 'Herzen', 'Allgemeinwissen');
  E('Wie lange ist ein Marathon in Kilometern?', 42.195, 'km', 'Allgemeinwissen');
  E('Wie viele Minuten dauert eine Halbzeit im Fußball?', 45, 'Minuten', 'Allgemeinwissen');
  E('Wie viele Saiten hat eine klassische Gitarre?', 6, 'Saiten', 'Allgemeinwissen');
  E('Wie viele Planeten hat unser Sonnensystem?', 8, 'Planeten', 'Allgemeinwissen');
  E('Wie viele Millimeter sind ein Zoll?', 25.4, 'mm', 'Allgemeinwissen');
  E('Wie viele Gramm hat ein Pfund in Deutschland?', 500, 'g', 'Allgemeinwissen');
  E('Wie viele Menschen leben ungefähr auf der Erde (in Milliarden)?', 8, 'Milliarden', 'Allgemeinwissen');
  E('Wie viele Stunden schläft ein Erwachsener im Schnitt pro Nacht?', 7, 'Stunden', 'Allgemeinwissen');
  E('Wie viele Kilokalorien hat ein Liter Vollmilch ungefähr?', 640, 'kcal', 'Allgemeinwissen');
  E('Wie viele Chromosomen hat ein Mensch?', 46, 'Chromosomen', 'Allgemeinwissen');
  E('Wie viele Nullen hat eine Milliarde?', 9, 'Nullen', 'Allgemeinwissen');
  E('Wie viele Quadratmeter hat ein Hektar?', 10000, 'm²', 'Allgemeinwissen');
  E('Wie viele Zeitzonen gibt es auf der Erde?', 24, 'Zeitzonen', 'Allgemeinwissen');
  E('Wie viele Muskeln braucht man ungefähr zum Lächeln?', 12, 'Muskeln', 'Allgemeinwissen');
  Y('In welchem Jahr fiel die Berliner Mauer?', 1989, 'Allgemeinwissen');
  Y('In welchem Jahr wurde der Euro als Bargeld eingeführt?', 2002, 'Allgemeinwissen');
  Y('In welchem Jahr landeten zum ersten Mal Menschen auf dem Mond?', 1969, 'Allgemeinwissen');
  Y('In welchem Jahr wurde das World Wide Web öffentlich freigegeben?', 1991, 'Allgemeinwissen');
  Y('In welchem Jahr endete der Zweite Weltkrieg?', 1945, 'Allgemeinwissen');
  Y('In welchem Jahr erschien das erste iPhone?', 2007, 'Allgemeinwissen');
  M('Welches Organ produziert Insulin?', ['Bauchspeicheldrüse', 'Leber', 'Niere', 'Milz'], 'Allgemeinwissen');
  M('Welches Gas atmen Menschen zum Leben ein?', ['Sauerstoff', 'Stickstoff', 'Kohlendioxid', 'Helium'], 'Allgemeinwissen');
  M('Was ist die Hauptzutat von Guacamole?', ['Avocado', 'Erbse', 'Zucchini', 'Spinat'], 'Allgemeinwissen');
  M('Welches Metall ist bei Zimmertemperatur flüssig?', ['Quecksilber', 'Blei', 'Zinn', 'Zink'], 'Allgemeinwissen');
  M('Wie heißt die längste Arterie des Menschen?', ['Aorta', 'Vene', 'Kapillare', 'Bronchie'], 'Allgemeinwissen');
  M('Welches Tier ist ein Säugetier?', ['Delfin', 'Hai', 'Krokodil', 'Pinguin'], 'Allgemeinwissen');
  M('Was misst ein Barometer?', ['Luftdruck', 'Temperatur', 'Windgeschwindigkeit', 'Lautstärke'], 'Allgemeinwissen');
  M('Welche Blutgruppe gilt als Universalspender?', ['0 negativ', 'AB positiv', 'A positiv', 'B negativ'], 'Allgemeinwissen');
  M('Was passiert beim Schmelzen?', ['Fest wird flüssig', 'Flüssig wird gasförmig', 'Gasförmig wird fest', 'Flüssig wird fest'], 'Allgemeinwissen');
  M('Welches Vitamin bildet der Körper durch Sonnenlicht?', ['Vitamin D', 'Vitamin C', 'Vitamin B12', 'Vitamin K'], 'Allgemeinwissen');
  M('Was ist Hefe?', ['Ein Pilz', 'Eine Bakterie', 'Eine Alge', 'Ein Mineral'], 'Allgemeinwissen');
  M('Welche Sprache hat weltweit die meisten Muttersprachler?', ['Chinesisch', 'Englisch', 'Spanisch', 'Hindi'], 'Allgemeinwissen');
  M('Was bedeutet die Abkürzung „PDF“?', ['Portable Document Format', 'Print Data File', 'Public Document Form', 'Personal Data Folder'], 'Allgemeinwissen');
  M('Womit wird traditionell Mozzarella hergestellt?', ['Büffelmilch', 'Ziegenmilch', 'Schafsmilch', 'Stutenmilch'], 'Allgemeinwissen');
  M('Was ist ein Palindrom?', ['Ein Wort, das rückwärts gleich ist', 'Ein Wort ohne Vokale', 'Ein zusammengesetztes Wort', 'Ein Fremdwort'], 'Allgemeinwissen');
  M('Wie viele Farben hat ein Regenbogen klassisch?', ['7', '5', '6', '8'], 'Allgemeinwissen');
  M('Welcher Muskel ist der stärkste im Verhältnis zu seiner Größe?', ['Kaumuskel', 'Bizeps', 'Wadenmuskel', 'Herzmuskel'], 'Allgemeinwissen');
  M('Was ist Kurkuma?', ['Ein Gewürz aus einer Wurzel', 'Eine Nussart', 'Ein Getreide', 'Eine Teesorte'], 'Allgemeinwissen');
};
