// News und Updates: neueste zuerst. Blöcke: head, text, list, cards, titles, emblems, badges, image
module.exports = [
  {
    id: 'u4-sammler',
    date: '2026-09-22T10:00:00+02:00',
    tag: 'Sammler-Update',
    title: 'Sammlung, Erfolge und mehr Überblick',
    teaser: 'Eine neue Rangliste für Kartensammler, Einblendungen bei neuen Erfolgen und ein Reiter mit allen Titeln, Emblemen und Rahmen.',
    hero: '/news/sammler_logo.webp',
    blocks: [
      { type: 'head', text: '✨ Rangliste „Sammlung“', badge: 'NEU' },
      { type: 'text', text: 'Wer hat die meisten verschiedenen Karten? Jede Karte zählt in jeder Fassung genau einmal, Doppelte bringen nichts. Seltene Fassungen geben mehr Punkte: Häufig 1, Selten 2, Holo 3, Ultra Rare 5, Legendär 8, Extended Art 12, Ghost Rare 15.' },
      { type: 'head', text: '🏅 Erfolge auf einen Blick', badge: 'NEU' },
      { type: 'list', items: ['Neue Herausforderungsstufen, Titel, Embleme und Rahmen werden kurz oben eingeblendet, egal wo du gerade bist', 'Ein Zähler am Knopf „Herausforderungen“ zeigt, was du noch nicht angesehen hast', 'Neuer Reiter „Titel, Embleme & Rahmen“ mit allen Stücken, ihrer Bedingung und deinem Fortschritt', 'Beim Antippen eines Titels oder Emblems siehst du deinen Stand, etwa 70 von 100 Siegen'] },
      { type: 'head', text: '🎩 Toon-Welt' },
      { type: 'text', text: '„Herrscher der Toon-Welt“ und das animierte Toon-Emblem gibt es jetzt erst mit allen 33 Toon-Karten, also allen 30 Karten plus den 3 Extended Arts.' },
      { type: 'head', text: '✨ Außerdem' },
      { type: 'list', items: ['🎡 Ein Zähler am Casino und am Glücksrad erinnert an deine freie Drehung', '👀 Solo-Matches kannst du jetzt zuschauen, auch direkt aus der Freundesliste', '💎 In der Casino-Rangliste und im Profil siehst du den Diamantenstand, kurz wie 1,2K oder 2M', 'ⓘ Neu: „So funktioniert’s“ erklärt alle Begriffe. Statistiken und Prestige-Bedingungen kannst du antippen, etwa was ein Doppel-Treffer ist: höchstens 4 % neben der Lösung, dafür doppelte Punkte', '❓ Gleiche Fragen in anderer Formulierung erkennt das Spiel und stellt sie dir nicht noch einmal', 'Kein Hochspringen mehr beim Antippen von Titeln und Emblemen im Profil'] },
    ],
  },
  {
    id: 'u3-poker',
    date: '2026-09-21T21:00:00+02:00',
    updated: '2026-09-21T23:00:00+02:00',
    tag: 'Casino-Update',
    title: 'Poker Night: Texas Hold\'em ist da',
    teaser: 'Zwei Pokertische für alle, neue animierte Titel, Spielzeit im Profil, Titel in den Ranglisten und Support-Tickets.',
    hero: '/news/poker_logo.webp',
    blocks: [
      { type: 'head', text: '♠️ Texas Hold\'em', badge: 'NEU' },
      { type: 'image', src: '/tcg/poker_high.webp', title: 'Zwei Tische, immer offen', text: 'Classic mit 150 💎 Einkauf und Blinds 5/10, High Stakes mit 1.500 💎 und Blinds 50/100. Setz dich hin oder schau erst zu, bis zu 6 Spieler pro Tisch. Beim Aufstehen bekommst du deine restlichen Chips zurück.' },
      { type: 'list', items: ['Tischmodus: Sobald du sitzt, passt der ganze Tisch mit deinen Karten und Knöpfen auf den Bildschirm', 'In der Tischmitte steht groß, was gerade passiert, etwa „Bot Luna erhöht auf 40“', 'Chips nach Werten wie im Casino, jede Farbe eine eigene Säule', '🤖 Auch solo spielbar: Sitzt du allein am Tisch, spielt ein Bot gegen dich. Kommt jemand dazu, geht der Bot nach der laufenden Hand', 'Chips liegen sichtbar vor jedem Spieler, Einsätze rutschen in die Mitte, der Pot fliegt zum Gewinner', 'Deine Karten und Knöpfe sitzen fest unten am Bildschirm, kein Scrollen mehr', 'Läuft deine Zeit ab, wird gefoldet. Kommst du zurück in die App, bist du sofort wieder im Spiel', 'Fold, Check, Call, Raise mit Schieberegler und All-in, echte Side Pots', 'Dealer-Button wandert, Zeitring von 20 Sekunden pro Zug', 'Freunde an den Tisch einladen, Emojis werfen, nach dem Pleitegehen nachkaufen', 'Poker gibt 25 % mehr Casino-XP, weil du gegen echte Gegner spielst', 'Zu finden im Casino unter „Poker ♠️“'] },
      { type: 'code', code: 'POKER', text: 'Löse den Code in deinem Profil ein und hol dir 10.000 Diamanten als Startkapital für die Pokertische.' },
      { type: 'head', text: '🏆 Neue Titel und Embleme' },
      { type: 'titles', items: [['TP1', 'Violetter Flush', '5 Stunden am Pokertisch · animiert'], ['TP2', 'Asse in Flammen', '150 gewonnene Hände · animiert'], ['TP3', 'König des Pokers', '1.500 gewonnene Hände · animiert']] },
      { type: 'emblems', items: [['EP1', 'Violetter Chipturm', '50 Hände'], ['EP2', 'Asse-Schild', 'Pot mit 5.000 💎'], ['EP3', 'Pokerkrone', 'Pot mit 60.000 💎 · animiert']] },
      { type: 'list', items: ['Fünf neue Herausforderungen im Casino: Sitzfleisch, Am Tisch, Pot-Jäger, Großer Pot und Alles oder nichts'] },
      { type: 'head', text: '⏱ Spielzeit' },
      { type: 'text', text: 'Ab jetzt zählt das Spiel mit, wie lange du online bist. Deine Spielzeit steht in deiner Statistik und in deinem Profil, auch andere sehen sie, wenn sie dein Profil öffnen. Die Zeit am Pokertisch wird extra gezählt.' },
      { type: 'head', text: '📊 Ranglisten' },
      { type: 'text', text: 'In allen Ranglisten steht unter jedem Namen jetzt auch der gewählte Titel, animiert wie im Profil.' },
      { type: 'head', text: '🎫 Support & Feedback' },
      { type: 'text', text: 'Ganz unten auf der Startseite findest du den Knopf „Support & Feedback“. Dort kannst du Tickets einreichen: 🐞 Fehler, 👤 Account oder 💡 Wunsch, mit Titel, Beschreibung und auf Wunsch einem Screenshot. Alle sehen alle Tickets mit farbigem Status: blau eingereicht, orange in Bearbeitung, grün abgeschlossen, rot abgelehnt. Wenn sich dein Ticket ändert, bekommst du eine Nachricht.' },
      { type: 'head', text: '✨ Außerdem' },
      { type: 'list', items: ['Herausforderungen antippen: alle Stufen, XP und die Belohnungen, die dranhängen', 'Börse mit eigenem Reiter „Verlauf“ und Push-Nachricht, wenn deine Karte verkauft wurde', 'Deutliche Anzeige in der Lobby, ob die Fragen fertig sind', 'Glücksrad heißt jetzt auch so im Casino'] },
    ],
  },
  {
    id: 'u2-hottime',
    date: '2026-09-21T16:45:00+02:00',
    tag: 'Update',
    title: 'Hot Time und nur noch frische Fragen',
    teaser: 'Jeden Abend doppelte XP und ein neuer Fragen-Motor ohne Wiederholungen.',
    hero: '/emblems/pc_EC3.webp',
    blocks: [
      { type: 'head', text: '🔥 Hot Time · 20 bis 24 Uhr', badge: 'NEU' },
      { type: 'list', items: ['Doppelte XP und Diamanten im Quiz, auch solo', 'Doppelte Casino-XP', 'Push um 19:59 Uhr, die Uhr auf der Startseite zeigt, wann es losgeht'] },
      { type: 'head', text: '✨ Nur noch frische Fragen', badge: 'NEU' },
      { type: 'list', items: ['Jede Runde nur mit gerade erstellten Fragen, kein alter Katalog mehr', 'Keine ähnlichen Fragen in einer Runde, keine Klassiker, keine Wiederholungen', 'Das Match startet, sobald die Fragen da sind'] },
      { type: 'head', text: '🃏 Außerdem' },
      { type: 'list', items: ['🎫 Support & Feedback ganz unten auf der Startseite: Fehler melden, Account-Hilfe, Wünsche, mit Screenshot', '💎 Börse mit Verlauf aller Verkäufe und Push-Nachricht, wenn deine Karte verkauft wurde', 'Herausforderungen antippen zeigt alle Stufen und Belohnungen', 'Toon-Welt-Booster jetzt im Shop', 'Mehr Abwechslung: höchstens eine Frage pro Autor, Werk oder Ort, keine Rechenfragen mehr', 'Blackjack: gewählter Einsatz leuchtet golden'] },
    ],
  },
  {
    id: 'u1-toonwelt',
    date: '2026-09-21T15:00:00+02:00',
    updated: '2026-09-21T17:15:00+02:00',
    tag: 'Großes Update',
    title: 'Toon-Welt, Casino-VIP und vieles mehr',
    teaser: 'Ein neues Kartenset in den Startlöchern, VIP-Stufen im Casino, Solo-Runden und Zufallsfunde.',
    hero: '/tcg/pack_toon.webp',
    blocks: [
      { type: 'head', text: '🎩 Toon-Welt', badge: 'JETZT DA' },
      { type: 'text', text: '30 neue Karten mit frechen Toon-Figuren, 3 davon zusätzlich als Extended Art. Booster für 2.000 Diamanten mit 2 Karten, jetzt im Shop.' },
      { type: 'cards', items: ['t01_legend', 't02_ext', 't03_legend', 't04_ultra', 't07_holo', 't11_selten'] },
      { type: 'titles', items: [['TT3', 'Herrscher der Toon-Welt', 'alle 33 Toon-Karten inkl. Extended Art · animiert']] },
      { type: 'text', text: 'Weitere Titel und Embleme gibt es für 5, 10, 15 und 20 Toon-Karten, dazu die Herausforderung Toon-Sammler.' },
      { type: 'head', text: '👑 Casino' },
      { type: 'badges', items: [[0, 'Bronze'], [1, 'Silber'], [2, 'Gold'], [3, 'Platin'], [4, 'Diamant'], [5, 'Black Card']] },
      { type: 'image', src: '/news/gluecksrad.webp', title: '🎡 Glücksrad', text: 'Einmal am Tag gratis drehen, ab Gold zweimal, ab Diamant dreimal. Diamanten, Booster und ein Jackpot.' },
      { type: 'image', src: '/tcg/wheel.webp', title: '🎲 Roulette', text: 'Komplettes Tableau, Chips bis 10k, All in und bis 250.000 pro Runde.' },
      { type: 'list', items: ['VIP-Stufen bis Black Card, Cashback ab Gold, sechs Tischdesigns', 'Blackjack mit allen Regeln und Tischen für mehrere Spieler'] },
      { type: 'code', code: 'GAMBLER', text: 'Löse den Code in deinem Profil ein und hol dir das komplette Casino-Paket plus 15.000 Diamanten.' },
      { type: 'titles', items: [['TC1', 'Diamantregen', 'Code GAMBLER · animiert'], ['TC2', 'Kartenkönig', 'Code GAMBLER · animiert'], ['TC3', 'Jackpot', 'Code GAMBLER · animiert'], ['THR', 'High Roller', '100.000 Diamanten auf einmal gewinnen']] },
      { type: 'emblems', items: [['EC1', 'Walzenkönig', 'Code GAMBLER'], ['EC2', 'Roulettekrone', 'Code GAMBLER'], ['EC3', 'Chipturm', 'Code GAMBLER']] },
      { type: 'head', text: '🎯 Solo und 🎁 Zufallsfunde' },
      { type: 'list', items: ['Solo spielen: fast volle XP und Diamanten, keine Ranglistenpunkte', 'Am Rundenende kann jeder Diamanten oder Booster finden, alle sehen es'] },
      { type: 'head', text: '✨ Neu im Spiel' },
      { type: 'list', items: ['Tagesbelohnung mit Boostern an Tag 3, 5 und 7', 'Erstes Match des Tages zählt doppelt', 'Großer Auftritt bei Extended Art und Ghost Rare', 'Neue Startseite, Herausforderungen nach Kategorien', 'Freunde zeigen, was sie gerade machen, Profile überall antippbar'] },
      { type: 'head', text: '🛠 Behoben' },
      { type: 'list', items: ['Titel und Diamanten überall aktuell', 'Roulette zeigt das Ergebnis erst, wenn die Kugel liegt', 'Kein Flackern mehr beim Wechseln'] },
    ],
  },
];
