// News und Updates: neueste zuerst. Blöcke: text, list, cards, titles, emblems, badges, image
module.exports = [
  {
    id: 'u1-toonwelt',
    date: '2026-09-21T15:00:00+02:00',
    updated: '2026-09-21T15:40:00+02:00',
    tag: 'Großes Update',
    title: 'Toon-Welt, Casino-VIP und vieles mehr',
    teaser: 'Ein neues Kartenset steht in den Startlöchern, das Casino bekommt VIP-Stufen und ein Glücksrad, dazu jede Menge Neues.',
    hero: '/tcg/pack_toon.webp',
    blocks: [
      { type: 'head', text: '🎩 Toon-Welt: das neue Kartenset', badge: 'BALD' },
      { type: 'text', text: 'Aus einem uralten Zauberbuch steigt die Toon-Welt: 30 neue Karten mit frechen Toon-Figuren, gemalt in edlem Fantasy-Stil. Magierinnen, Zeitmagier, Drachen, Dinokaiser und ein Maßbandkobold, der sehr genau wissen will, wer am nächsten dran war.' },
      { type: 'cards', items: ['t01_legend', 't02_ext', 't03_legend', 't04_ultra', 't07_holo', 't11_selten'] },
      { type: 'list', items: ['30 Karten in zwei neuen Rahmen: Toon-Grimoire und Arcane', '3 Karten zusätzlich als Extended Art im neuen, klaren Vollbild-Stil', 'Toon-Welt-Booster: 2.000 Diamanten, 2 Karten, nur Toon-Karten', 'Extended Art kommt im Schnitt etwa einmal in 100 Boostern', 'Der Booster ist schon im Shop zu sehen und wird bald freigeschaltet'] },
      { type: 'head', text: '🏆 Belohnungen fürs Sammeln' },
      { type: 'text', text: 'Wer die Toon-Welt sammelt, schaltet eigene Titel und Embleme frei. Wer alle 30 Karten hat, bekommt die animierten Spitzenstücke.' },
      { type: 'titles', items: [['TT1', 'Toon-Leser', '5 verschiedene Toon-Karten'], ['TT2', 'Toon-Zauberer', '15 verschiedene Toon-Karten'], ['TT3', 'Herrscher der Toon-Welt', 'alle 30 Toon-Karten · animiert']] },
      { type: 'emblems', items: [['ET1', 'Toon-Grimoire', '10 Karten'], ['ET2', 'Arcane-Siegel', '20 Karten'], ['ET3', 'Herr der Toon-Welt', 'alle 30 · animiert']] },
      { type: 'list', items: ['Neue Herausforderung Toon-Sammler mit sechs Stufen und bis zu 6.400 XP', 'In der Sammlung gibt es einen eigenen Filter für jedes Booster-Set, samt Fortschritt'] },
      { type: 'head', text: '👑 Casino: VIP-Stufen, Glücksrad und mehr' },
      { type: 'badges', items: [[0, 'Bronze'], [1, 'Silber'], [2, 'Gold'], [3, 'Platin'], [4, 'Diamant'], [5, 'Black Card']] },
      { type: 'image', src: '/news/gluecksrad.webp', title: '🎡 Das Glücksrad', text: 'Einmal am Tag gratis drehen: Diamanten von 50 bis 2.500, Standard-, Premium- und Geister-Booster und ganz selten der Jackpot mit 5.000 Diamanten. Ab Gold darfst du zweimal drehen, ab Diamant dreimal. Du findest es im Casino unter VIP.' },
      { type: 'image', src: '/tcg/wheel.webp', title: '🎲 Das neue Roulette', text: 'Ein echter Kessel mit gegenläufiger Kugel und das komplette Tableau: einzelne Zahlen, Split, Street, Ecke, Sechserreihe, Dutzende, Kolonnen, Rot, Schwarz und mehr. Chips von 10 bis 10.000 und All in, bis zu 250.000 pro Runde. Gesetzte Chips gehen sofort vom Stand ab, oben erscheint kurz, was gefallen ist und ob du gewonnen hast.' },
      { type: 'list', items: ['Casino-XP füllen sechs VIP-Stufen bis zur Black Card, sichtbar in der Rangliste und am Tisch', 'Tägliches Glücksrad, höhere Stufen dürfen öfter drehen', 'Cashback ab Gold: ein Teil der Verluste vom Vortag kommt zurück', 'Sechs Tischdesigns bis zu Schwarz-Gold', 'Blackjack mit Teilen, Verdoppeln, Versicherung und Mehrspieler-Tischen', 'Roulette-Tableau mit allen Einsatzarten, Chips bis 10k, All in und bis zu 250.000 pro Runde', 'Neue Casino-Titel: High Roller und das Casino-Paket mit dem Code GAMBLER'] },
      { type: 'titles', items: [['THR', 'High Roller', '100.000 Diamanten auf einmal gewinnen'], ['TC1', 'Diamantregen', 'Code GAMBLER']] },
      { type: 'head', text: '🎯 Solo spielen', badge: 'NEU' },
      { type: 'text', text: 'Keiner online? Kein Problem. Mit „Solo spielen“ startest du sofort eine eigene Runde im freien Spiel, mit Themen deiner Wahl. Niemand kann beitreten, und es geht direkt los.' },
      { type: 'list', items: ['Du sammelst XP und Diamanten, etwas weniger als in einer Runde mit anderen', 'Keine Ranglistenpunkte, die gibt es nur im Ranglisten-Modus', 'Das doppelte erste Match des Tages gilt auch solo'] },
      { type: 'head', text: '🎁 Zufallsfunde', badge: 'NEU' },
      { type: 'text', text: 'Am Ende jeder Runde kann jeder Mitspieler etwas finden: Diamanten, einen Standard-, Premium- oder sogar Geister-Booster, und ganz selten einen Jackpot mit 3.000 Diamanten. Alle sehen im Endstand, wer was gefunden hat.' },
      { type: 'list', items: ['Etwa jeder Fünfte findet am Ende einer Runde mit anderen etwas', 'In Solo-Runden gibt es seltener Funde', 'Booster landen direkt in deinem Inventar'] },
      { type: 'head', text: '🏠 Neue Startseite' },
      { type: 'list', items: ['News & Updates ganz oben, damit du nichts verpasst', 'Deine Spielerkarte direkt darunter, mit großem Knopf zum Bearbeiten', 'Match eröffnen, Solo spielen und deine Freunde gleich darunter', 'Herausforderungen als eigener Bereich, sortiert nach Toon-Welt, Allgemein, Sammeln und Casino', 'Neue Spieler kompakt: die zwei neuesten sofort, weitere zum Aufklappen'] },
      { type: 'head', text: '✨ Neu im Spiel' },
      { type: 'list', items: ['Tagesbelohnung mit steigenden Diamanten und Boostern an Tag 3, 5 und 7', 'Dein erstes Match am Tag zählt doppelt: XP und Diamanten', 'Großer Auftritt, wenn du eine Extended Art oder Ghost Rare ziehst', 'Freunde und Online-Spieler zeigen, was sie gerade machen', 'Profile überall antippbar, Freunde direkt aus jeder Liste hinzufügen', 'Neue Spieler auf der Startseite, Offline-Freunde zum Aufklappen', 'Doppelte Karten gezielt umwandeln, Sammlung nach Booster filtern'] },
      { type: 'head', text: '🛠 Behoben' },
      { type: 'list', items: ['Roulette zieht gesetzte Chips sofort vom Stand ab, der Gewinn kommt, wenn die Kugel liegt', 'Kurze Ergebnis-Meldung beim Roulette statt eines Fensters zum Wegklicken', 'Titel und Embleme werden überall angezeigt, auch in der Lobby', 'Diamanten sind überall sofort aktuell', 'Kein Flackern mehr beim Wechseln zwischen Bereichen', 'KI-Fragen kommen deutlich zuverlässiger'] },
    ],
  },
];
