// News und Updates: neueste zuerst. Blöcke: head, text, list, cards, titles, emblems, badges, image
module.exports = [
  {
    id: 'u2-hottime',
    date: '2026-09-21T16:45:00+02:00',
    tag: 'Update',
    title: 'Hot Time und nur noch frische Fragen',
    teaser: 'Jeden Abend doppelte XP und ein neuer Fragen-Motor ohne Wiederholungen.',
    hero: '/emblems/pc_EC3.webp',
    blocks: [
      { type: 'head', text: '🔥 Hot Time · 20 bis 24 Uhr', badge: 'NEU' },
      { type: 'list', items: ['Doppelte XP und Diamanten im Quiz, auch solo', 'Doppelte Casino-XP', 'Push um 19:59 Uhr, die Uhr auf der Startseite zeigt, wann es losgeht'] },
      { type: 'head', text: '✨ Nur noch frische Fragen', badge: 'NEU' },
      { type: 'list', items: ['Jede Runde nur mit gerade erstellten Fragen, kein alter Katalog mehr', 'Keine ähnlichen Fragen in einer Runde, keine Klassiker, keine Wiederholungen', 'Das Match startet, sobald die Fragen da sind'] },
      { type: 'head', text: '🃏 Außerdem' },
      { type: 'list', items: ['Toon-Welt-Booster jetzt im Shop', 'Mehr Abwechslung: höchstens eine Frage pro Autor, Werk oder Ort, keine Rechenfragen mehr', 'Blackjack: gewählter Einsatz leuchtet golden'] },
    ],
  },
  {
    id: 'u1-toonwelt',
    date: '2026-09-21T15:00:00+02:00',
    updated: '2026-09-21T17:15:00+02:00',
    tag: 'Großes Update',
    title: 'Toon-Welt, Casino-VIP und vieles mehr',
    teaser: 'Ein neues Kartenset in den Startlöchern, VIP-Stufen im Casino, Solo-Runden und Zufallsfunde.',
    hero: '/tcg/pack_toon.webp',
    blocks: [
      { type: 'head', text: '🎩 Toon-Welt', badge: 'JETZT DA' },
      { type: 'text', text: '30 neue Karten mit frechen Toon-Figuren, 3 davon zusätzlich als Extended Art. Booster für 2.000 Diamanten mit 2 Karten, jetzt im Shop.' },
      { type: 'cards', items: ['t01_legend', 't02_ext', 't03_legend', 't04_ultra', 't07_holo', 't11_selten'] },
      { type: 'titles', items: [['TT3', 'Herrscher der Toon-Welt', 'alle 30 Toon-Karten · animiert']] },
      { type: 'text', text: 'Weitere Titel und Embleme gibt es für 5, 10, 15 und 20 Toon-Karten, dazu die Herausforderung Toon-Sammler.' },
      { type: 'head', text: '👑 Casino' },
      { type: 'badges', items: [[0, 'Bronze'], [1, 'Silber'], [2, 'Gold'], [3, 'Platin'], [4, 'Diamant'], [5, 'Black Card']] },
      { type: 'image', src: '/news/gluecksrad.webp', title: '🎡 Glücksrad', text: 'Einmal am Tag gratis drehen, ab Gold zweimal, ab Diamant dreimal. Diamanten, Booster und ein Jackpot.' },
      { type: 'image', src: '/tcg/wheel.webp', title: '🎲 Roulette', text: 'Komplettes Tableau, Chips bis 10k, All in und bis 250.000 pro Runde.' },
      { type: 'list', items: ['VIP-Stufen bis Black Card, Cashback ab Gold, sechs Tischdesigns', 'Blackjack mit allen Regeln und Tischen für mehrere Spieler', 'Titel High Roller und das Casino-Paket mit dem Code GAMBLER'] },
      { type: 'head', text: '🎯 Solo und 🎁 Zufallsfunde' },
      { type: 'list', items: ['Solo spielen: fast volle XP und Diamanten, keine Ranglistenpunkte', 'Am Rundenende kann jeder Diamanten oder Booster finden, alle sehen es'] },
      { type: 'head', text: '✨ Neu im Spiel' },
      { type: 'list', items: ['Tagesbelohnung mit Boostern an Tag 3, 5 und 7', 'Erstes Match des Tages zählt doppelt', 'Großer Auftritt bei Extended Art und Ghost Rare', 'Neue Startseite, Herausforderungen nach Kategorien', 'Freunde zeigen, was sie gerade machen, Profile überall antippbar'] },
      { type: 'head', text: '🛠 Behoben' },
      { type: 'list', items: ['Titel und Diamanten überall aktuell', 'Roulette zeigt das Ergebnis erst, wenn die Kugel liegt', 'Kein Flackern mehr beim Wechseln'] },
    ],
  },
];
