// Fester Fragenpool. E = Schätzfrage, M = Auswahlfrage (erste Option ist richtig, wird beim Ausspielen gemischt).
// range = absolute Abweichung, ab der es 0 Punkte gibt (Standard: 50 % der Antwort).
const pool = [];
let n = 0;
const E = (q, a, unit, cat, range) => pool.push({ id: 'p' + (++n), t: 'est', q, a, unit, cat, range });
const M = (q, o, cat) => pool.push({ id: 'p' + (++n), t: 'mc', q, o, cat });
const yearRange = (y) => (y >= 1900 ? 20 : y >= 1800 ? 35 : y >= 1400 ? 70 : 150);
const Y = (q, a, cat = 'Geschichte') => E(q, a, 'Jahr', cat, yearRange(a));

// Bauwerke & Höhen
E('Wie hoch ist der Eiffelturm inklusive Antenne?', 330, 'm', 'Bauwerke');
E('Wie viele Stufen führen bis zur Spitze des Eiffelturms?', 1665, 'Stufen', 'Bauwerke');
E('Wie hoch ist der Kölner Dom?', 157, 'm', 'Bauwerke');
E('Wie hoch ist der Burj Khalifa in Dubai?', 828, 'm', 'Bauwerke');
E('Wie hoch ist der Berliner Fernsehturm?', 368, 'm', 'Bauwerke');
E('Wie hoch ist der Turm des Ulmer Münsters, der höchste Kirchturm der Welt?', 161.5, 'm', 'Bauwerke');
E('Wie hoch ist die Freiheitsstatue inklusive Sockel?', 93, 'm', 'Bauwerke');
E('Wie hoch ist die Cheops-Pyramide heute?', 139, 'm', 'Bauwerke');
E('Wie lang ist die Golden Gate Bridge insgesamt?', 2737, 'm', 'Bauwerke');
E('Wie lang ist der Gotthard-Basistunnel?', 57, 'km', 'Bauwerke');
E('Wie lang ist der Eurotunnel unter dem Ärmelkanal?', 50, 'km', 'Bauwerke');
E('Wie lang ist die Chinesische Mauer mit allen Abschnitten laut offizieller Vermessung?', 21196, 'km', 'Bauwerke');
E('Wie lang war die Titanic?', 269, 'm', 'Bauwerke');
E('Wie groß ist die Spannweite eines Airbus A380?', 79.8, 'm', 'Technik');

// Geografie
E('Wie hoch ist der Mount Everest?', 8849, 'm', 'Geografie');
E('Wie hoch ist die Zugspitze?', 2962, 'm', 'Geografie');
E('Wie hoch ist der Kilimandscharo?', 5895, 'm', 'Geografie');
E('Wie hoch ist das Matterhorn?', 4478, 'm', 'Geografie');
E('Wie hoch ist der Großglockner?', 3798, 'm', 'Geografie');
E('Wie hoch ist der Brocken im Harz?', 1141, 'm', 'Geografie');
E('Wie hoch ist der Feldberg im Schwarzwald?', 1493, 'm', 'Geografie');
E('Wie lang ist der Rhein?', 1233, 'km', 'Geografie');
E('Wie lang ist die Donau?', 2857, 'km', 'Geografie');
E('Wie lang ist der Nil?', 6650, 'km', 'Geografie');
E('Wie groß ist die Fläche des Bodensees?', 536, 'km²', 'Geografie');
E('Wie tief ist der Bodensee an seiner tiefsten Stelle?', 251, 'm', 'Geografie');
E('Wie tief ist der Baikalsee an seiner tiefsten Stelle?', 1642, 'm', 'Geografie');
E('Wie groß ist die Fläche Deutschlands, in Tausend km²?', 358, 'Tsd. km²', 'Geografie');
E('Wie groß ist die Fläche Russlands?', 17.1, 'Mio. km²', 'Geografie');
E('Wie groß ist die Sahara ungefähr?', 9.2, 'Mio. km²', 'Geografie');
E('Wie viele Staaten sind Mitglied der Vereinten Nationen?', 193, 'Staaten', 'Geografie');
E('Wie viele Mitgliedstaaten hat die EU?', 27, 'Staaten', 'Geografie');
E('Wie viele Länder gibt es in Afrika?', 54, 'Länder', 'Geografie');
E('Wie viele Zeitzonen hat Russland?', 11, 'Zeitzonen', 'Geografie');
E('Wie viel Prozent der Erdoberfläche sind von Wasser bedeckt?', 71, '%', 'Geografie');
E('Wie lang ist das deutsche Autobahnnetz ungefähr?', 13200, 'km', 'Geografie');
E('Welche Temperatur wurde als höchste jemals auf der Erde gemessen (Death Valley)?', 56.7, '°C', 'Geografie');

// Weltall & Naturwissenschaft
E('Wie schnell ist das Licht?', 299792, 'km/s', 'Wissenschaft');
E('Wie schnell ist der Schall in Luft bei 20 °C?', 343, 'm/s', 'Wissenschaft');
E('Wie viele Sekunden braucht das Licht von der Sonne zur Erde?', 499, 's', 'Weltall');
E('Wie weit ist der Mond im Mittel von der Erde entfernt?', 384400, 'km', 'Weltall');
E('Wie weit ist die Sonne im Mittel von der Erde entfernt?', 150, 'Mio. km', 'Weltall');
E('Wie groß ist der Durchmesser der Erde am Äquator?', 12756, 'km', 'Weltall');
E('Wie groß ist der Erdumfang am Äquator?', 40075, 'km', 'Weltall');
E('Wie groß ist der Durchmesser des Mondes?', 3474, 'km', 'Weltall');
E('Wie groß ist der Durchmesser der Sonne?', 1.39, 'Mio. km', 'Weltall');
E('Wie alt ist das Universum?', 13.8, 'Mrd. Jahre', 'Weltall');
E('Wie alt ist die Erde?', 4.5, 'Mrd. Jahre', 'Weltall');
E('Wie schnell fliegt die ISS um die Erde?', 27600, 'km/h', 'Weltall');
E('In welcher Höhe fliegt die ISS ungefähr?', 400, 'km', 'Weltall');
E('Wie heiß ist die Oberfläche der Sonne ungefähr?', 5500, '°C', 'Weltall');
E('Bei welcher Temperatur schmilzt Eisen?', 1538, '°C', 'Wissenschaft');
E('Bei welcher Temperatur schmilzt Gold?', 1064, '°C', 'Wissenschaft');
E('Welche Dichte hat Gold?', 19.3, 'g/cm³', 'Wissenschaft');
E('Wie viel wiegt ein Standard-Goldbarren (400 Unzen)?', 12.4, 'kg', 'Wissenschaft');
E('Wie viele Elemente hat das Periodensystem?', 118, 'Elemente', 'Wissenschaft');
E('Welche Ordnungszahl hat Gold?', 79, '', 'Wissenschaft');
E('Wie viel Prozent der Luft sind Sauerstoff?', 21, '%', 'Wissenschaft');
E('Wie viel Prozent der Luft sind Stickstoff?', 78, '%', 'Wissenschaft');
E('Wie viel ist 2 hoch 20?', 1048576, '', 'Mathe');
E('Wie viele Sekunden hat ein Tag?', 86400, 's', 'Mathe');
E('Wie viele Minuten hat eine Woche?', 10080, 'min', 'Mathe');
E('Wie viele Stunden hat ein Jahr mit 365 Tagen?', 8760, 'h', 'Mathe');

// Mensch & Tier
E('Wie viele Knochen hat ein erwachsener Mensch?', 206, 'Knochen', 'Mensch');
E('Wie viele Chromosomen hat eine menschliche Körperzelle?', 46, 'Chromosomen', 'Mensch');
E('Wie viele Wochen dauert eine Schwangerschaft rechnerisch?', 40, 'Wochen', 'Mensch');
E('Wie viele Monate trägt eine Afrikanische Elefantenkuh ihr Kalb aus?', 22, 'Monate', 'Tiere');

// Sport
E('Wie lang ist ein Marathon?', 42195, 'm', 'Sport');
E('Wie breit ist ein Fußballtor?', 7.32, 'm', 'Sport');
E('Wie hoch ist ein Fußballtor?', 2.44, 'm', 'Sport');
E('Wie hoch hängt ein Basketballkorb?', 3.05, 'm', 'Sport');
E('Wie lang ist ein Tennisplatz?', 23.77, 'm', 'Sport');
E('Wie hoch ist ein Tischtennisnetz?', 15.25, 'cm', 'Sport');
E('Wie lautet der 100-Meter-Weltrekord von Usain Bolt?', 9.58, 's', 'Sport');
E('Wie weit sprang Mike Powell bei seinem Weitsprung-Weltrekord?', 8.95, 'm', 'Sport');
E('Wie hoch sprang Javier Sotomayor bei seinem Hochsprung-Weltrekord?', 2.45, 'm', 'Sport');
E('Wie viele Länderspieltore schoss Miroslav Klose für Deutschland?', 71, 'Tore', 'Sport');
E('Wie viele Bundesligatore schoss Gerd Müller?', 365, 'Tore', 'Sport');
E('Wie viele Tore schoss Robert Lewandowski in seiner Rekordsaison 2020/21 in der Bundesliga?', 41, 'Tore', 'Sport');
E('Wie viele Zuschauer passen bei Bundesligaspielen in den Signal Iduna Park?', 81365, 'Plätze', 'Sport');
E('Wie viele Zuschauer passen bei Bundesligaspielen in die Allianz Arena?', 75024, 'Plätze', 'Sport');
E('Wie lang ist die Nürburgring-Nordschleife?', 20.8, 'km', 'Sport');
E('Wie hoch ist das höchstmögliche Break beim Snooker?', 147, 'Punkte', 'Sport');
E('Wie viele Punkte sind beim Darts mit drei Pfeilen maximal möglich?', 180, 'Punkte', 'Sport');
E('Wie viele Spieler stehen beim Rugby Union pro Team auf dem Feld?', 15, 'Spieler', 'Sport');
E('Wie schnell fuhr der TGV bei seinem Weltrekord 2007?', 574.8, 'km/h', 'Technik');

// Spiele & Kultur
E('Wie viele Tasten hat ein Klavier?', 88, 'Tasten', 'Kultur');
E('Wie viele Felder hat ein Schachbrett?', 64, 'Felder', 'Spiele');
E('Wie viele Felder hat ein Sudoku?', 81, 'Felder', 'Spiele');
E('Wie viele Felder hat das Monopoly-Spielbrett?', 40, 'Felder', 'Spiele');
E('Wie viele Karten hat ein Skatblatt?', 32, 'Karten', 'Spiele');
E('Wie viele Augen hat ein Würfel insgesamt?', 21, 'Augen', 'Spiele');
E('Wie viele Steine hat ein Standard-Dominospiel (Doppel-6)?', 28, 'Steine', 'Spiele');
E('Wie viele Sterne hat die Europaflagge?', 12, 'Sterne', 'Kultur');
E('Wie viele Streifen hat die Flagge der USA?', 13, 'Streifen', 'Kultur');
E('Wie viele Oscars gewann „Der Herr der Ringe: Die Rückkehr des Königs“?', 11, 'Oscars', 'Kultur');
E('Wie alt wurde Wolfgang Amadeus Mozart?', 35, 'Jahre', 'Kultur');

// Jahreszahlen
Y('In welchem Jahr fiel die Berliner Mauer?', 1989);
Y('In welchem Jahr landeten die ersten Menschen auf dem Mond?', 1969);
Y('In welchem Jahr sank die Titanic?', 1912);
Y('In welchem Jahr erreichte Kolumbus Amerika?', 1492);
Y('In welchem Jahr begann die Französische Revolution?', 1789);
Y('In welchem Jahr wurde die Bundesrepublik Deutschland gegründet?', 1949);
Y('In welchem Jahr wurde das Euro-Bargeld eingeführt?', 2002);
Y('In welchem Jahr wurde die D-Mark eingeführt?', 1948);
Y('In welchem Jahr war die deutsche Wiedervereinigung?', 1990);
Y('In welchem Jahr wurde das Deutsche Kaiserreich gegründet?', 1871);
Y('In welchem Jahr veröffentlichte Luther seine 95 Thesen?', 1517);
Y('In welchem Jahr endete der Dreißigjährige Krieg?', 1648);
Y('In welchem Jahr wurde Karl der Große zum Kaiser gekrönt?', 800);
Y('In welchem Jahr endete das Weströmische Reich?', 476);
Y('In welchem Jahr wurde das bayerische Reinheitsgebot erlassen?', 1516);
Y('In welchem Jahr fand das erste Oktoberfest statt?', 1810);
Y('In welchem Jahr war die Reaktorkatastrophe von Tschernobyl?', 1986);
Y('In welchem Jahr wurde der Mount Everest erstmals bestiegen?', 1953);
Y('In welchem Jahr gelang den Brüdern Wright der erste Motorflug?', 1903);
Y('In welchem Jahr veröffentlichte Einstein die spezielle Relativitätstheorie?', 1905);
Y('In welchem Jahr erhielt Alexander Graham Bell das Patent auf das Telefon?', 1876);
Y('In welchem Jahr meldete Carl Benz seinen Motorwagen zum Patent an?', 1886, 'Auto');
Y('In welchem Jahr entstand die Daimler-Benz AG durch Fusion?', 1926, 'Auto');
Y('In welchem Jahr wurde das Mercedes-Benz-Werk Sindelfingen gegründet?', 1915, 'Auto');
Y('In welchem Jahr schlug Tim Berners-Lee das World Wide Web vor?', 1989, 'Technik');
Y('In welchem Jahr kam das erste iPhone auf den Markt?', 2007, 'Technik');
Y('In welchem Jahr wurde Google gegründet?', 1998, 'Technik');
Y('In welchem Jahr wurde Apple gegründet?', 1976, 'Technik');
Y('In welchem Jahr wurde Microsoft gegründet?', 1975, 'Technik');
Y('In welchem Jahr wurde Amazon gegründet?', 1994, 'Technik');
Y('In welchem Jahr ging YouTube online?', 2005, 'Technik');
Y('In welchem Jahr startete die Fußball-Bundesliga?', 1963, 'Sport');
Y('In welchem Jahr fand die erste Tour de France statt?', 1903, 'Sport');
Y('In welchem Jahr fanden die ersten Olympischen Spiele der Neuzeit statt?', 1896, 'Sport');

// Auswahlfragen
M('Wie heißt die Hauptstadt von Australien?', ['Canberra', 'Sydney', 'Melbourne', 'Perth'], 'Geografie');
M('Wie heißt die Hauptstadt von Kanada?', ['Ottawa', 'Toronto', 'Vancouver', 'Montreal'], 'Geografie');
M('Wie heißt die Hauptstadt der Türkei?', ['Ankara', 'Istanbul', 'Izmir', 'Antalya'], 'Geografie');
M('Wie heißt die Hauptstadt von Brasilien?', ['Brasília', 'Rio de Janeiro', 'São Paulo', 'Salvador'], 'Geografie');
M('Durch welche Hauptstadt fließt die Donau?', ['Budapest', 'Prag', 'Warschau', 'Rom'], 'Geografie');
M('Welches Land hat die größte Fläche?', ['Russland', 'Kanada', 'China', 'USA'], 'Geografie');
M('Welcher ist der größte Ozean?', ['Pazifik', 'Atlantik', 'Indischer Ozean', 'Arktischer Ozean'], 'Geografie');
M('Welche ist die größte Wüste der Erde, Eiswüsten eingeschlossen?', ['Antarktis', 'Sahara', 'Gobi', 'Arabische Wüste'], 'Geografie');
M('Welcher Kontinent hat die meisten Länder?', ['Afrika', 'Asien', 'Europa', 'Südamerika'], 'Geografie');
M('Welches Land hat mit seinen Überseegebieten die meisten Zeitzonen?', ['Frankreich', 'Russland', 'USA', 'China'], 'Geografie');
M('Wie heißt der höchste Wasserfall der Erde?', ['Salto Ángel', 'Niagarafälle', 'Victoriafälle', 'Iguazú-Fälle'], 'Geografie');
M('In welcher Stadt steht die Sagrada Família?', ['Barcelona', 'Madrid', 'Lissabon', 'Sevilla'], 'Geografie');
M('Welcher ist der größte Planet unseres Sonnensystems?', ['Jupiter', 'Saturn', 'Neptun', 'Uranus'], 'Weltall');
M('Welcher Planet ist der Sonne am nächsten?', ['Merkur', 'Venus', 'Mars', 'Erde'], 'Weltall');
M('Welches chemische Symbol hat Eisen?', ['Fe', 'Ei', 'Ir', 'Es'], 'Wissenschaft');
M('Welches chemische Symbol hat Gold?', ['Au', 'Go', 'Ag', 'Gd'], 'Wissenschaft');
M('Welches chemische Symbol hat Natrium?', ['Na', 'Nt', 'N', 'Ni'], 'Wissenschaft');
M('Welches Gas ist der Hauptbestandteil der Luft?', ['Stickstoff', 'Sauerstoff', 'Kohlendioxid', 'Argon'], 'Wissenschaft');
M('Welches ist das härteste natürliche Material?', ['Diamant', 'Granit', 'Quarz', 'Titan'], 'Wissenschaft');
M('In welcher Einheit misst man den elektrischen Widerstand?', ['Ohm', 'Volt', 'Ampere', 'Watt'], 'Technik');
M('Was misst man in Hertz?', ['Frequenz', 'Spannung', 'Leistung', 'Helligkeit'], 'Technik');
M('Welches Organ produziert Insulin?', ['Bauchspeicheldrüse', 'Leber', 'Niere', 'Milz'], 'Mensch');
M('Welcher ist der längste Knochen des Menschen?', ['Oberschenkelknochen', 'Schienbein', 'Oberarmknochen', 'Wadenbein'], 'Mensch');
M('Welche Blutgruppe gilt als Universalspender für rote Blutkörperchen?', ['0 negativ', 'AB positiv', 'A negativ', 'B positiv'], 'Mensch');
M('Wie viele Herzen hat ein Oktopus?', ['3', '1', '2', '4'], 'Tiere');
M('Welches ist das schnellste Landtier?', ['Gepard', 'Löwe', 'Antilope', 'Windhund'], 'Tiere');
M('Welches ist das größte Säugetier?', ['Blauwal', 'Afrikanischer Elefant', 'Pottwal', 'Giraffe'], 'Tiere');
M('Wer malte die Mona Lisa?', ['Leonardo da Vinci', 'Michelangelo', 'Raffael', 'Botticelli'], 'Kultur');
M('Wer schrieb „Faust“?', ['Goethe', 'Schiller', 'Lessing', 'Heine'], 'Kultur');
M('Wer komponierte „Die Zauberflöte“?', ['Mozart', 'Beethoven', 'Haydn', 'Wagner'], 'Kultur');
M('Was ist die Hauptzutat von Guacamole?', ['Avocado', 'Erbsen', 'Gurke', 'Spinat'], 'Kultur');
M('Welche Währung hat Japan?', ['Yen', 'Won', 'Yuan', 'Baht'], 'Geografie');
M('Wer wurde 2018 Fußball-Weltmeister?', ['Frankreich', 'Kroatien', 'Deutschland', 'Brasilien'], 'Sport');
M('Wer wurde 2022 Fußball-Weltmeister?', ['Argentinien', 'Frankreich', 'Kroatien', 'Marokko'], 'Sport');
M('Wie viele Spieler pro Team stehen beim Volleyball auf dem Feld?', ['6', '5', '7', '8'], 'Sport');
M('Wer meldete 1886 das erste Automobil zum Patent an?', ['Carl Benz', 'Gottlieb Daimler', 'Henry Ford', 'Rudolf Diesel'], 'Auto');
M('Welcher Hersteller wirbt mit „Das Beste oder nichts“?', ['Mercedes-Benz', 'BMW', 'Audi', 'Porsche'], 'Auto');
M('In welcher Stadt hat Porsche seinen Hauptsitz?', ['Stuttgart', 'München', 'Wolfsburg', 'Ingolstadt'], 'Auto');
M('Welche Sprache führen Webbrowser nativ aus?', ['JavaScript', 'Python', 'Java', 'C#'], 'Technik');

// Musik
E('Wie viele Saiten hat eine Standard-Gitarre?', 6, 'Saiten', 'Musik');
E('Wie viele Saiten hat eine Geige?', 4, 'Saiten', 'Musik');
E('Wie viele weiße Tasten hat ein Klavier?', 52, 'Tasten', 'Musik');
E('Wie viele Musiker gehörten zu den Beatles?', 4, 'Musiker', 'Musik');
E('Wie viele Studioalben veröffentlichten die Beatles offiziell in Großbritannien?', 12, 'Alben', 'Musik');
E('Wie lang ist „Bohemian Rhapsody“ von Queen?', 355, 's', 'Musik');
E('Wie viele Grammys gewann Michael Jackson für „Thriller“ bei der Verleihung 1984?', 8, 'Grammys', 'Musik');
E('Wie alt wurde Elvis Presley?', 42, 'Jahre', 'Musik');
E('Wie alt wurde Ludwig van Beethoven?', 56, 'Jahre', 'Musik');
E('Wie viele Sinfonien komponierte Beethoven?', 9, 'Sinfonien', 'Musik');
E('Wie viele Länder nahmen 2023 am Eurovision Song Contest teil?', 37, 'Länder', 'Musik');
E('Wie viele Siege hat Irland beim Eurovision Song Contest?', 7, 'Siege', 'Musik');
Y('In welchem Jahr gewann Nicole für Deutschland den Grand Prix mit „Ein bisschen Frieden“?', 1982, 'Musik');
Y('In welchem Jahr gewann Lena den Eurovision Song Contest?', 2010, 'Musik');
Y('In welchem Jahr erschien Michael Jacksons Album „Thriller“?', 1982, 'Musik');
Y('In welchem Jahr trennten sich die Beatles offiziell?', 1970, 'Musik');
Y('In welchem Jahr starb Freddie Mercury?', 1991, 'Musik');
Y('In welchem Jahr fand das Woodstock-Festival statt?', 1969, 'Musik');
Y('In welchem Jahr wurde die Compact Disc auf dem Markt eingeführt?', 1982, 'Musik');
Y('In welchem Jahr startete Spotify in Deutschland?', 2012, 'Musik');
M('Wer sang „Like a Rolling Stone“?', ['Bob Dylan', 'Neil Young', 'Johnny Cash', 'Bruce Springsteen'], 'Musik');
M('Welche Band veröffentlichte „The Dark Side of the Moon“?', ['Pink Floyd', 'Led Zeppelin', 'The Who', 'Genesis'], 'Musik');
M('Wer komponierte die „Kleine Nachtmusik“?', ['Mozart', 'Bach', 'Haydn', 'Schubert'], 'Musik');
M('Welches Instrument spielte Louis Armstrong hauptsächlich?', ['Trompete', 'Saxofon', 'Posaune', 'Klarinette'], 'Musik');
M('Wie hieß die Band von Kurt Cobain?', ['Nirvana', 'Pearl Jam', 'Soundgarden', 'Alice in Chains'], 'Musik');
M('Aus welcher Stadt stammt die Band Oasis?', ['Manchester', 'London', 'Liverpool', 'Leeds'], 'Musik');
M('Wer sang „Purple Rain“?', ['Prince', 'Lenny Kravitz', 'Stevie Wonder', 'Marvin Gaye'], 'Musik');
M('Welcher deutsche Rapper veröffentlichte das Album „Palmen aus Plastik“ gemeinsam mit Bonez MC?', ['RAF Camora', 'Capital Bra', 'Kollegah', 'Sido'], 'Musik');
M('Welche Band singt „Du hast“?', ['Rammstein', 'Die Toten Hosen', 'Böhse Onkelz', 'Die Ärzte'], 'Musik');
M('Wie viele Töne hat eine Dur-Tonleiter ohne den Oktavton?', ['7', '5', '8', '12'], 'Musik');

// Call of Duty
Y('In welchem Jahr erschien das erste Call of Duty?', 2003, 'Call of Duty');
Y('In welchem Jahr erschien Call of Duty 4: Modern Warfare?', 2007, 'Call of Duty');
Y('In welchem Jahr erschien Call of Duty: Modern Warfare 2?', 2009, 'Call of Duty');
Y('In welchem Jahr erschien das erste Call of Duty: Black Ops?', 2010, 'Call of Duty');
Y('In welchem Jahr erschien Call of Duty: Warzone?', 2020, 'Call of Duty');
Y('In welchem Jahr erschien Call of Duty: WWII?', 2017, 'Call of Duty');
E('Wie viele Prestige-Stufen hat Call of Duty: Modern Warfare 2 von 2009?', 10, 'Stufen', 'Call of Duty');
E('Welchen Höchstrang erreicht man in Modern Warfare 2 (2009) innerhalb eines Prestiges?', 70, 'Rang', 'Call of Duty');
E('Wie viele Abschüsse in Folge braucht man in Modern Warfare 2 für den Tactical Nuke?', 25, 'Abschüsse', 'Call of Duty');
E('Wie viele Spieler starteten in der ersten Warzone-Runde auf Verdansk?', 150, 'Spieler', 'Call of Duty');
E('Wie viele Spieler passen bei Warzone in einen Trupp im Quads-Modus?', 4, 'Spieler', 'Call of Duty');
M('In welchem Studio entstand die Black-Ops-Reihe?', ['Treyarch', 'Infinity Ward', 'Sledgehammer Games', 'Raven Software'], 'Call of Duty');
M('Welches Studio entwickelte das erste Modern Warfare?', ['Infinity Ward', 'Treyarch', 'Sledgehammer Games', 'Beenox'], 'Call of Duty');
M('Wie heißt der Erzfeind in Call of Duty 4: Modern Warfare?', ['Imran Zakhaev', 'Vladimir Makarov', 'Raul Menendez', 'Gabriel Rorke'], 'Call of Duty');
M('Wie heißt der Antagonist in Modern Warfare 2 von 2009?', ['Vladimir Makarov', 'Imran Zakhaev', 'Khaled Al-Asad', 'Raul Menendez'], 'Call of Duty');
M('Wie lautet der Nachname von Soap aus der Modern-Warfare-Reihe?', ['MacTavish', 'Riley', 'Garrick', 'Vasquez'], 'Call of Duty');
M('In welchem Call of Duty wurde der Zombies-Modus erstmals eingeführt?', ['World at War', 'Black Ops', 'Modern Warfare 2', 'Black Ops II'], 'Call of Duty');
M('Wie heißt die große Karte aus Call of Duty: Warzone von 2020?', ['Verdansk', 'Al Mazrah', 'Caldera', 'Rebirth Island'], 'Call of Duty');
M('Welche Karte aus Modern Warfare 2 spielt in einem Vorort mit einer Tankstelle?', ['Terminal', 'Rust', 'Highrise', 'Favela'], 'Call of Duty');
M('Wie heißt die kleine Wüstenkarte aus Modern Warfare 2, die für 1-gegen-1 beliebt ist?', ['Rust', 'Shipment', 'Nuketown', 'Dome'], 'Call of Duty');
M('Wie heißt die bekannte kleine Karte aus der Black-Ops-Reihe mit zwei Häusern?', ['Nuketown', 'Firing Range', 'Summit', 'Hijacked'], 'Call of Duty');
M('Welcher Publisher steht hinter Call of Duty?', ['Activision', 'Electronic Arts', 'Ubisoft', 'Take-Two'], 'Call of Duty');

// BookTok (nur Bücher ab 2000, TikTok-tauglich)
Y('In welchem Jahr erschien „Fourth Wing“ von Rebecca Yarros?', 2023, 'BookTok');
Y('In welchem Jahr erschien „Iron Flame“, der zweite Band der Empyrean-Reihe?', 2023, 'BookTok');
Y('In welchem Jahr erschien „It Ends With Us“ von Colleen Hoover im Original?', 2016, 'BookTok');
Y('In welchem Jahr erschien „Verity“ von Colleen Hoover im Original?', 2018, 'BookTok');
Y('In welchem Jahr erschien „Ugly Love“ von Colleen Hoover im Original?', 2014, 'BookTok');
Y('In welchem Jahr erschien „Das Lied des Achill“ von Madeline Miller im Original?', 2011, 'BookTok');
Y('In welchem Jahr erschien „A Court of Thorns and Roses“ im Original?', 2015, 'BookTok');
Y('In welchem Jahr erschien „Die sieben Männer der Evelyn Hugo“ im Original?', 2017, 'BookTok');
Y('In welchem Jahr erschien „Der Gesang der Flusskrebse“ im Original?', 2018, 'BookTok');
Y('In welchem Jahr erschien „Die Mitternachtsbibliothek“ von Matt Haig im Original?', 2020, 'BookTok');
Y('In welchem Jahr erschien „The Love Hypothesis“ von Ali Hazelwood?', 2021, 'BookTok');
Y('In welchem Jahr erschien „Die Tribute von Panem“ im Original?', 2008, 'BookTok');
Y('In welchem Jahr erschien „Twilight – Bis(s) zum Morgengrauen“ im Original?', 2005, 'BookTok');
Y('In welchem Jahr erschien „Das Schicksal ist ein mieser Verräter“ im Original?', 2012, 'BookTok');
Y('In welchem Jahr erschien „Throne of Glass“ von Sarah J. Maas im Original?', 2012, 'BookTok');
Y('In welchem Jahr erschien „Shatter Me“ von Tahereh Mafi im Original?', 2011, 'BookTok');
Y('In welchem Jahr erschien „Six of Crows“ von Leigh Bardugo?', 2015, 'BookTok');
Y('In welchem Jahr erschien „The Cruel Prince“ von Holly Black?', 2018, 'BookTok');
Y('In welchem Jahr erschien „Normal People“ von Sally Rooney?', 2018, 'BookTok');
Y('In welchem Jahr erschien „It Starts With Us“, die Fortsetzung von „It Ends With Us“?', 2022, 'BookTok');
E('Wie viele Bücher hat die Hauptreihe „A Court of Thorns and Roses“ bisher?', 5, 'Bücher', 'BookTok');
E('Wie viele Bände hat die Reihe „Die Tribute von Panem“ ohne Vorgeschichten?', 3, 'Bände', 'BookTok');
E('Wie viele Bücher umfasst die Twilight-Hauptreihe?', 4, 'Bücher', 'BookTok');
E('Wie viele Bände hat die Grisha-Trilogie von Leigh Bardugo?', 3, 'Bände', 'BookTok');
M('Wer schrieb „Das Lied des Achill“?', ['Madeline Miller', 'Sally Rooney', 'Colleen Hoover', 'Taylor Jenkins Reid'], 'BookTok');
M('Wer schrieb „It Ends With Us“?', ['Colleen Hoover', 'Ali Hazelwood', 'Emily Henry', 'Jojo Moyes'], 'BookTok');
M('Wer schrieb die Reihe „Das Reich der sieben Höfe“?', ['Sarah J. Maas', 'Rebecca Yarros', 'Leigh Bardugo', 'Holly Black'], 'BookTok');
M('Wer schrieb „Fourth Wing“?', ['Rebecca Yarros', 'Sarah J. Maas', 'Jennifer L. Armentrout', 'Cassandra Clare'], 'BookTok');
M('Wer schrieb „Die sieben Männer der Evelyn Hugo“?', ['Taylor Jenkins Reid', 'Colleen Hoover', 'Emily Henry', 'Delia Owens'], 'BookTok');
M('Wer schrieb „Der Gesang der Flusskrebse“?', ['Delia Owens', 'Kristin Hannah', 'Bonnie Garmus', 'Celeste Ng'], 'BookTok');
M('Wer schrieb „Die Mitternachtsbibliothek“?', ['Matt Haig', 'Fredrik Backman', 'Mitch Albom', 'Paulo Coelho'], 'BookTok');
M('Wer schrieb „The Love Hypothesis“?', ['Ali Hazelwood', 'Emily Henry', 'Colleen Hoover', 'Tessa Bailey'], 'BookTok');
M('Wer schrieb „Six of Crows“?', ['Leigh Bardugo', 'Victoria Aveyard', 'Stephanie Garber', 'Marissa Meyer'], 'BookTok');
M('Wer schrieb „Eine Frage der Chemie“?', ['Bonnie Garmus', 'Delia Owens', 'Gail Honeyman', 'Taylor Jenkins Reid'], 'BookTok');
M('Wer schrieb „Caraval“?', ['Stephanie Garber', 'Holly Black', 'Leigh Bardugo', 'Sarah J. Maas'], 'BookTok');
M('Wer schrieb „Normal People“?', ['Sally Rooney', 'Emily Henry', 'Coco Mellors', 'Dolly Alderton'], 'BookTok');
M('Wie heißt der Drache von Violet in „Fourth Wing“?', ['Tairn', 'Andarna', 'Sgaeyl', 'Feirge'], 'BookTok');
M('Wie heißt die Kriegsschule in „Fourth Wing“?', ['Basgiath', 'Velaris', 'Ketterdam', 'Prythian'], 'BookTok');
M('In welcher Stadt spielt „Six of Crows“?', ['Ketterdam', 'Velaris', 'Erilea', 'Panem'], 'BookTok');
M('Wie heißt der männliche Hauptcharakter in „It Ends With Us“?', ['Ryle', 'Atlas', 'Rhysand', 'Xaden'], 'BookTok');
M('Welches Genre hat auf TikTok als „Romantasy“ Karriere gemacht?', ['Fantasy mit Liebesgeschichte', 'Wirtschaftskrimi', 'Reisebericht', 'Historische Biografie'], 'BookTok');

// GRACE: Fragen über Grace, nur während der Aktion aktiv
E('Wie viel wog Grace bei ihrer Geburt?', 3284, 'g', 'GRACE');
E('Wie groß war Grace bei ihrer Geburt?', 51, 'cm', 'GRACE');
E('An welchem Tag im September wurde Grace geboren?', 17, 'Tag', 'GRACE');
Y('In welchem Jahr wurde Grace geboren?', 2023, 'GRACE');
E('Um wie viel Uhr wurde Grace geboren? Nur die Stunde.', 4, 'Uhr', 'GRACE');
E('Wie viele Minuten nach 4 Uhr wurde Grace geboren?', 22, 'min', 'GRACE');
E('Welchen Geburtstag hat Grace gerade gefeiert?', 3, 'Jahre', 'GRACE');
E('Wie schwer ist Grace heute ungefähr?', 15, 'kg', 'GRACE');
E('Wie groß ist Grace heute ungefähr?', 100, 'cm', 'GRACE');
E('Mit wie vielen Monaten bekam Grace ihren ersten Zahn?', 4, 'Monate', 'GRACE');
E('Wie viele Katzen leben bei Grace?', 2, 'Katzen', 'GRACE');
E('Um wie viel Uhr steht Grace im Schnitt auf? Nur die Stunde.', 7, 'Uhr', 'GRACE');
E('In welchem Monat kam Grace in den Kindergarten?', 8, 'Monat', 'GRACE');
M('Wie heißt Graces Lieblings-Tonie?', ['Herr H', 'Benjamin Blümchen', 'Bibi Blocksberg', 'Der kleine Rabe Socke'], 'GRACE');
M('Wie heißt Graces Kuscheltier?', ['Basket', 'Bommel', 'Knuffel', 'Pucki'], 'GRACE');
M('Welche Serie schaut Grace nach PAW Patrol am liebsten?', ['Barbapapa', 'Peppa Wutz', 'Die Maus', 'Bluey'], 'GRACE');
M('Welche PAW-Patrol-Figur mag Grace gerade am liebsten?', ['Rex', 'Chase', 'Marshall', 'Skye'], 'GRACE');
M('Welches Wort benutzt Grace statt „Wurst“?', ['Fleisch', 'Salami', 'Schinken', 'Wurschti'], 'GRACE');
M('Was isst Grace am liebsten zum Frühstück?', ['Käse', 'Müsli', 'Marmeladenbrot', 'Joghurt'], 'GRACE');
M('Was mag Grace überhaupt nicht essen?', ['Salat', 'Nudeln', 'Kartoffeln', 'Apfel'], 'GRACE');
M('Welche Süßigkeit liebt Grace besonders?', ['Esspapier', 'Lakritz', 'Schokoriegel', 'Bonbons'], 'GRACE');
M('Wie heißt Graces Kindergarten?', ['Wurzelzwerge', 'Sonnenkäfer', 'Regenbogen', 'Pusteblume'], 'GRACE');
M('Wie heißt Graces Erzieherin?', ['Silke', 'Sabine', 'Simone', 'Sandra'], 'GRACE');
M('Wie heißen Graces Katzen?', ['Felix und Franky', 'Felix und Fritzi', 'Filou und Franky', 'Fussel und Frida'], 'GRACE');
M('In welcher Stadt wurde Grace geboren?', ['Mülheim an der Ruhr', 'Duisburg', 'Essen', 'Oberhausen'], 'GRACE');
M('In welchem Krankenhaus kam Grace zur Welt?', ['Evangelisches Krankenhaus', 'St. Marien-Hospital', 'Universitätsklinikum', 'Helios Klinikum'], 'GRACE');
M('Welche Farben greift Grace zuerst?', ['Pink und Lila', 'Blau und Grün', 'Rot und Gelb', 'Schwarz und Weiß'], 'GRACE');
M('Welches Motto hatte Graces erster Geburtstag?', ['Tanzende Früchte', 'Einhörner', 'Dschungel', 'Regenbogen'], 'GRACE');
M('Welches Motto hatte Graces zweiter Geburtstag?', ['Too Sweet', 'Dino-Party', 'Zirkus', 'Unter dem Meer'], 'GRACE');
M('Wann konnte Grace laufen?', ['Vor ihrem ersten Geburtstag', 'Kurz nach dem ersten Geburtstag', 'Mit eineinhalb Jahren', 'Mit zwei Jahren'], 'GRACE');
M('Wie sprach Grace früher das Wort „Kaffee“ aus?', ['Paffee', 'Taffee', 'Baffee', 'Gaffee'], 'GRACE');
M('Welchen Buchstaben ersetzte Grace früher am Wortanfang durch ein P?', ['K', 'T', 'B', 'G'], 'GRACE');
M('Um wie viel Uhr geht Grace im Schnitt schlafen?', ['19:45 Uhr', '18:30 Uhr', '20:30 Uhr', '21:00 Uhr'], 'GRACE');
M('Hat Grace einen zweiten Vornamen?', ['Nein, sie hat nur einen', 'Ja, Marie', 'Ja, Sophie', 'Ja, Luna'], 'GRACE');

module.exports = { pool, yearRange };
