// Sammelkarten: Definitionen, Booster, Ziehen. Die Duell-Logik kommt später.
const CARDS = [
  { id: 'kobold',  name: 'Zollstock-Kobold',  theme: 'Technik', lvl: 3, atk: 900,  def: 700,  set: 'standard', base: 'haeufig',
    effect: 'Wenn diese Karte zerstört wird: Ziehe 1 Karte.' },
  { id: 'falke',   name: 'Stoppuhr-Falke',    theme: 'Sport',   lvl: 4, atk: 1200, def: 800,  set: 'premium', base: 'haeufig',
    effect: 'Einmal pro Zug: Erhöhe die ATK einer eigenen Karte bis zum Zugende um 300.' },
  { id: 'golem',   name: 'Zahnrad-Golem',     theme: 'Technik', lvl: 5, atk: 1700, def: 2000, set: 'standard', base: 'selten',
    effect: 'Solange diese Karte in Verteidigung liegt, verlieren alle gegnerischen Karten 200 DEF.' },
  { id: 'orakel',  name: 'Eiskristall-Orakel', theme: 'Wissen', lvl: 6, atk: 2100, def: 1900, set: 'premium', base: 'selten',
    effect: 'Einmal pro Zug: Sieh dir die oberste Karte im Deck des Gegners an und lege sie zurück.' },
  { id: 'drache',  name: 'Maßband-Drache',    theme: 'Weltall', lvl: 8, atk: 3000, def: 2500, set: 'standard', base: 'legend',
    effect: 'Wenn diese Karte beschworen wird: Zerstöre 1 gegnerische Karte mit weniger als 2000 ATK.' },
  { id: 'schmied', name: 'Sternenschmied',    theme: 'Weltall', lvl: 9, atk: 3200, def: 2800, set: 'premium', base: 'legend',
    effect: 'Einmal pro Duell: Hole 1 Karte mit bis zu 4 Sternen aus deinem Friedhof zurück.' },
  { id: 'eisfee', name: 'Eisfee', theme: 'Wissen', lvl: 4, atk: 1300, def: 1100, set: 'standard', base: 'haeufig',
    effect: 'Einmal pro Zug: Friere 1 gegnerische Karte bis zum Ende des nächsten Zuges ein.' },
  { id: 'einhorn', name: 'Morgenlicht-Einhorn', theme: 'Wissen', lvl: 6, atk: 2000, def: 2100, set: 'standard', base: 'selten',
    effect: 'Wenn diese Karte beschworen wird: Heile 500 Lebenspunkte.' },
  { id: 'sternpanther', name: 'Sternenpanther', theme: 'Weltall', lvl: 7, atk: 2400, def: 1800, set: 'premium', base: 'selten',
    effect: 'Diese Karte kann nicht als Ziel von Effekten gewählt werden.' },
  { id: 'domgolem', name: 'Kathedralen-Golem', theme: 'Bauwerke', lvl: 8, atk: 2800, def: 3000, set: 'standard', base: 'legend',
    effect: 'Solange diese Karte liegt, erleiden eigene Karten in Verteidigung keinen Kampfschaden.' },
  { id: 'astroritter', name: 'Astro-Ritter', theme: 'Weltall', lvl: 5, atk: 1800, def: 1600, set: 'standard', base: 'selten',
    effect: 'Einmal pro Zug: Wechsle die Position einer gegnerischen Karte.' },
  { id: 'inselschildkroete', name: 'Inselschildkröte', theme: 'Geografie', lvl: 7, atk: 2000, def: 2900, set: 'premium', base: 'selten',
    effect: 'Solange diese Karte liegt, erhalten alle eigenen Karten 300 DEF.' },
  { id: 'schildmaid', name: 'Runen-Schildmaid', theme: 'Geschichte', lvl: 6, atk: 2200, def: 1500, set: 'standard', base: 'selten',
    effect: 'Wenn diese Karte eine Karte zerstört: Ziehe 1 Karte.' },
  { id: 'gepardwagen', name: 'Gepard-Bolide', theme: 'Technik', lvl: 5, atk: 1900, def: 1200, set: 'premium', base: 'selten',
    effect: 'Diese Karte kann im Zug der Beschwörung sofort angreifen.' },
  { id: 'notentaenzerin', name: 'Notentänzerin', theme: 'Musik', lvl: 4, atk: 1400, def: 1400, set: 'premium', base: 'haeufig',
    effect: 'Einmal pro Zug: Tausche ATK und DEF einer eigenen Karte bis zum Zugende.' },
  { id: 'nachtoperator', name: 'Nacht-Operator', theme: 'Call of Duty', lvl: 6, atk: 2300, def: 1400, set: 'standard', base: 'selten',
    effect: 'Einmal pro Duell: Zerstöre 1 gedeckte gegnerische Karte.' },
  { id: 'entschaerfer', name: 'Entschärfer', theme: 'Counter-Strike', lvl: 5, atk: 1600, def: 2100, set: 'premium', base: 'selten',
    effect: 'Einmal pro Zug: Negiere den Effekt einer gegnerischen Karte bis zum Zugende.' },
  { id: 'buechermagierin', name: 'Büchermagierin', theme: 'BookTok', lvl: 6, atk: 1900, def: 2200, set: 'standard', base: 'selten',
    effect: 'Einmal pro Zug: Lege 1 Karte aus deiner Hand ab und ziehe 2 Karten.' },
  { id: 'blaetterphoenix', name: 'Blätterphönix', theme: 'Wissen', lvl: 8, atk: 2900, def: 2400, set: 'premium', base: 'legend',
    effect: 'Wenn diese Karte zerstört wird: Beschwöre sie am Ende des nächsten Zuges zurück.' },
  { id: 'meerkoenigin', name: 'Perlen-Königin', theme: 'Geografie', lvl: 7, atk: 2500, def: 2300, set: 'premium', base: 'selten',
    effect: 'Einmal pro Zug: Nimm 1 eigene Karte auf die Hand zurück.' },
  { id: 'uhreule', name: 'Uhrwerk-Eule', theme: 'Technik', lvl: 4, atk: 1200, def: 1700, set: 'standard', base: 'haeufig',
    effect: 'Wenn diese Karte beschworen wird: Sieh dir die Hand des Gegners an.' },
  { id: 'sphinx', name: 'Wüsten-Sphinx', theme: 'Geschichte', lvl: 7, atk: 2600, def: 2200, set: 'standard', base: 'selten',
    effect: 'Der Gegner muss ein Rätsel lösen: Er wirft eine Münze, bei Kopf kann er angreifen.' },
  { id: 'sturmriese', name: 'Sturmriese', theme: 'Weltall', lvl: 9, atk: 3100, def: 2600, set: 'standard', base: 'legend',
    effect: 'Wenn diese Karte angreift: Zerstöre zusätzlich 1 gegnerische Karte mit weniger als 1500 DEF.' },
  { id: 'gartenfee', name: 'Gartenfee', theme: 'Wissen', lvl: 3, atk: 800, def: 900, set: 'premium', base: 'haeufig',
    effect: 'Wenn diese Karte zerstört wird: Beschwöre 1 Karte mit bis zu 3 Sternen aus deinem Deck.' },
  { id: 'fuchssamurai', name: 'Fuchs-Samurai', theme: 'Geschichte', lvl: 6, atk: 2100, def: 1700, set: 'premium', base: 'selten',
    effect: 'Diese Karte greift zweimal an, wenn sie eine Karte mit weniger ATK angreift.' },
  { id: 'torjaeger', name: 'Torjäger', theme: 'Sport', lvl: 5, atk: 1800, def: 1300, set: 'standard', base: 'selten',
    effect: 'Einmal pro Zug: Erhöhe die ATK dieser Karte um 400, bis sie angreift.' },
  { id: 'kristallhirsch', name: 'Kristallhirsch', theme: 'Wissen', lvl: 6, atk: 1700, def: 2400, set: 'premium', base: 'selten',
    effect: 'Solange diese Karte liegt, kann der Gegner keine Karten mit 4 Sternen oder weniger angreifen.' },
  { id: 'luftschifferin', name: 'Luftschiff-Kapitänin', theme: 'Technik', lvl: 6, atk: 2000, def: 1900, set: 'standard', base: 'selten',
    effect: 'Einmal pro Zug: Lege 1 Karte vom Deck des Gegners beiseite.' },
  { id: 'cyberkatze', name: 'Cyber-Katze', theme: 'Technik', lvl: 4, atk: 1500, def: 1000, set: 'standard', base: 'haeufig',
    effect: 'Wenn diese Karte beschworen wird: Sieh dir 3 Karten deines Decks an und nimm 1 auf die Hand.' },
  { id: 'goldskarabaeus', name: 'Gold-Skarabäus', theme: 'Geschichte', lvl: 5, atk: 1600, def: 1800, set: 'premium', base: 'selten',
    effect: 'Solange diese Karte liegt, erhältst du bei jeder eigenen Beschwörung 200 Lebenspunkte.' },
  { id: 'leuchtturm', name: 'Leuchtturm-Wächter', theme: 'Geografie', set: 'standard', lvl: 6, atk: 2000, def: 2200, base: 'selten',
    effect: 'Solange diese Karte liegt, kann der Gegner keine gedeckten Karten angreifen.' },
  { id: 'blumenfee', name: 'Blütenkönigin', theme: 'Wissen', set: 'premium', lvl: 7, atk: 2300, def: 2500, base: 'selten',
    effect: 'Einmal pro Zug: Gib einer eigenen Karte 500 DEF bis zum Zugende.' },
  { id: 'schneeleopard', name: 'Schneeleopard-Krieger', theme: 'Geografie', set: 'standard', lvl: 6, atk: 2200, def: 1800, base: 'selten',
    effect: 'Wenn diese Karte angreift: Der Gegner kann keine Effekte aktivieren.' },
  { id: 'kolibri', name: 'Glasflügel-Kolibri', theme: 'Technik', set: 'premium', lvl: 3, atk: 1000, def: 900, base: 'haeufig',
    effect: 'Wenn diese Karte beschworen wird: Ziehe 1 Karte, wenn du weniger Karten hast als der Gegner.' },
  { id: 'piratin', name: 'Freibeuterin', theme: 'Geschichte', set: 'standard', lvl: 6, atk: 2100, def: 1600, base: 'selten',
    effect: 'Wenn diese Karte eine Karte zerstört: Nimm dem Gegner 1 Karte aus der Hand.' },
  { id: 'lavatitan', name: 'Lava-Titan', theme: 'Weltall', set: 'premium', lvl: 9, atk: 3100, def: 2700, base: 'legend',
    effect: 'Wenn diese Karte beschworen wird: Zerstöre alle Karten mit weniger als 1500 DEF.' },
  { id: 'frosttaenzerin', name: 'Frosttänzerin', theme: 'Musik', set: 'standard', lvl: 4, atk: 1300, def: 1500, base: 'haeufig',
    effect: 'Einmal pro Zug: Setze den Angriff einer gegnerischen Karte aus.' },
  { id: 'rallyefahrer', name: 'Dünen-Rallye', theme: 'Sport', set: 'premium', lvl: 5, atk: 1900, def: 1100, base: 'selten',
    effect: 'Diese Karte kann direkt angreifen, wenn der Gegner keine Karte in Verteidigung hat.' },
  { id: 'gelehrter', name: 'Schildkröten-Gelehrter', theme: 'Wissen', set: 'standard', lvl: 5, atk: 1400, def: 2300, base: 'selten',
    effect: 'Einmal pro Zug: Sieh dir die obersten 2 Karten deines Decks an und ordne sie neu.' },
  { id: 'mondhase', name: 'Mondhasen-Alchemist', theme: 'Weltall', set: 'premium', lvl: 4, atk: 1200, def: 1400, base: 'haeufig',
    effect: 'Einmal pro Zug: Wirf eine Münze. Bei Kopf ziehe 1 Karte.' },
  { id: 'donnervogel', name: 'Donnervogel', theme: 'Weltall', set: 'standard', lvl: 8, atk: 2900, def: 2300, base: 'legend',
    effect: 'Wenn diese Karte angreift: Füge zusätzlich 500 Schaden zu.' },
  { id: 'vampirin', name: 'Nachtgräfin', theme: 'Geschichte', set: 'premium', lvl: 7, atk: 2500, def: 2000, base: 'selten',
    effect: 'Wenn diese Karte eine Karte zerstört: Heile 500 Lebenspunkte.' },
  { id: 'himmelwal', name: 'Himmelswal', theme: 'Weltall', set: 'premium', lvl: 8, atk: 2700, def: 2900, base: 'legend',
    effect: 'Solange diese Karte liegt, erhalten alle eigenen Karten 300 ATK.' },
  { id: 'sonnenblume', name: 'Sonnenblumen-Geist', theme: 'Wissen', set: 'standard', lvl: 3, atk: 900, def: 1100, base: 'haeufig',
    effect: 'Wenn diese Karte beschworen wird: Heile 300 Lebenspunkte.' },
  { id: 'tafelritter', name: 'Tafelritter', theme: 'Geschichte', set: 'premium', lvl: 6, atk: 2200, def: 2000, base: 'selten',
    effect: 'Einmal pro Zug: Diese Karte kann nicht zerstört werden.' },
  { id: 'kochbot', name: 'Küchen-Bot', theme: 'Technik', set: 'standard', lvl: 4, atk: 1400, def: 1200, base: 'haeufig',
    effect: 'Einmal pro Zug: Lege 1 Karte ab und ziehe 1 Karte.' },
  { id: 'quallenhexe', name: 'Quallenhexe', theme: 'Geografie', set: 'premium', lvl: 6, atk: 2000, def: 2400, base: 'selten',
    effect: 'Wenn diese Karte angegriffen wird: Der Angreifer verliert 400 ATK.' },
  { id: 'brueckentroll', name: 'Brückentroll', theme: 'Geschichte', set: 'standard', lvl: 5, atk: 1800, def: 2200, base: 'selten',
    effect: 'Der Gegner muss 1 Karte ablegen, um diese Karte anzugreifen.' },
  { id: 'eiskunst', name: 'Eiskunstläuferin', theme: 'Sport', set: 'premium', lvl: 4, atk: 1300, def: 1600, base: 'haeufig',
    effect: 'Einmal pro Zug: Wechsle diese Karte in die andere Position, ohne Kosten.' },
  { id: 'wuestennomade', name: 'Wüstennomade', theme: 'Geografie', set: 'standard', lvl: 5, atk: 1900, def: 1500, base: 'selten',
    effect: 'Wenn diese Karte beschworen wird: Sieh dir die oberste Karte beider Decks an.' },
  { id: 'zuckerhexe', name: 'Zuckerhexe', theme: 'BookTok', set: 'premium', lvl: 5, atk: 1700, def: 1800, base: 'selten',
    effect: 'Einmal pro Zug: Gib einer gegnerischen Karte 500 weniger ATK bis zum Zugende.' },
  { id: 'kampfmech', name: 'Kampf-Mech', theme: 'Call of Duty', set: 'standard', lvl: 8, atk: 3000, def: 2600, base: 'legend',
    effect: 'Wenn diese Karte angreift: Der Gegner kann keine Fallen aktivieren.' },
  { id: 'waldruidin', name: 'Walddruidin', theme: 'Wissen', set: 'premium', lvl: 6, atk: 2100, def: 2300, base: 'selten',
    effect: 'Einmal pro Zug: Beschwöre 1 Karte mit bis zu 3 Sternen aus deinem Friedhof.' },
  { id: 'greif', name: 'Goldener Greif', theme: 'Bauwerke', set: 'standard', lvl: 7, atk: 2500, def: 2100, base: 'selten',
    effect: 'Diese Karte kann angreifen, ohne die Position zu ändern.' },
  { id: 'laternenfuchs', name: 'Laternenfuchs', theme: 'Geschichte', set: 'premium', lvl: 6, atk: 2100, def: 1900, base: 'selten',
    effect: 'Einmal pro Zug: Sieh dir 1 gedeckte gegnerische Karte an.' },
  { id: 'luftpiratin', name: 'Luftpiratin', theme: 'Technik', set: 'standard', lvl: 5, atk: 1800, def: 1400, base: 'selten',
    effect: 'Wenn diese Karte beschworen wird: Nimm 1 Karte vom Friedhof auf die Hand.' },
  { id: 'kristallspinne', name: 'Kristallspinne', theme: 'Wissen', set: 'premium', lvl: 4, atk: 1200, def: 1600, base: 'haeufig',
    effect: 'Solange diese Karte liegt, kann der Gegner höchstens einmal pro Zug angreifen.' },
  { id: 'dunker', name: 'Dunk-König', theme: 'Sport', set: 'standard', lvl: 5, atk: 2000, def: 1200, base: 'selten',
    effect: 'Diese Karte erhält 300 ATK für jede eigene Karte auf dem Feld.' },
  { id: 'teegeist', name: 'Teegeist', theme: 'Wissen', set: 'premium', lvl: 3, atk: 800, def: 1300, base: 'haeufig',
    effect: 'Wenn diese Karte beschworen wird: Heile 400 Lebenspunkte.' },
  { id: 'nashornpanzer', name: 'Nashorn-Panzer', theme: 'Call of Duty', set: 'standard', lvl: 7, atk: 2600, def: 2400, base: 'selten',
    effect: 'Diese Karte kann nicht durch Kampf zerstört werden, wenn sie in Verteidigung liegt.' },
  { id: 'rosenritterin', name: 'Rosenritterin', theme: 'Geschichte', set: 'premium', lvl: 6, atk: 2200, def: 2100, base: 'selten',
    effect: 'Wenn diese Karte eine Karte zerstört: Heile 300 Lebenspunkte.' },
  { id: 'lavasalamander', name: 'Lava-Salamander', theme: 'Weltall', set: 'standard', lvl: 4, atk: 1500, def: 1000, base: 'haeufig',
    effect: 'Wenn diese Karte zerstört wird: Füge dem Gegner 400 Schaden zu.' },
  { id: 'plattenmagier', name: 'Platten-Magier', theme: 'Musik', set: 'premium', lvl: 5, atk: 1700, def: 1700, base: 'selten',
    effect: 'Einmal pro Zug: Tausche die Position aller Karten auf dem Feld.' },
  { id: 'polarwolf', name: 'Polarwolf-Rudel', theme: 'Geografie', set: 'standard', lvl: 6, atk: 2200, def: 1700, base: 'selten',
    effect: 'Solange diese Karte liegt, erhalten eigene Karten mit 4 Sternen oder weniger 400 ATK.' },
  { id: 'porzellanpuppe', name: 'Porzellanpuppe', theme: 'BookTok', set: 'premium', lvl: 5, atk: 1900, def: 1300, base: 'selten',
    effect: 'Einmal pro Duell: Zerstöre 1 Karte, die gerade beschworen wurde.' },
  { id: 'buecherdrache', name: 'Bücherdrache', theme: 'BookTok', set: 'standard', lvl: 9, atk: 3000, def: 2800, base: 'legend',
    effect: 'Einmal pro Zug: Ziehe 1 Karte für jede eigene zerstörte Karte in diesem Zug.' },
  { id: 'schmiedezwerg', name: 'Schmiedezwerg', theme: 'Technik', set: 'premium', lvl: 5, atk: 1800, def: 1900, base: 'selten',
    effect: 'Einmal pro Zug: Gib einer eigenen Karte 600 ATK bis zum Zugende.' },
  { id: 'schmetterling', name: 'Schmetterlings-Kaiserin', theme: 'Wissen', set: 'standard', lvl: 7, atk: 2400, def: 2400, base: 'selten',
    effect: 'Einmal pro Zug: Nimm 1 gegnerische Karte mit bis zu 4 Sternen auf die Hand zurück.' },
  { id: 'scharfschuetze', name: 'Scharfschütze', theme: 'Counter-Strike', set: 'premium', lvl: 6, atk: 2300, def: 1500, base: 'selten',
    effect: 'Wenn diese Karte angreift: Die angegriffene Karte verliert 800 DEF.' },
  { id: 'magmagolem', name: 'Magma-Golem', theme: 'Bauwerke', set: 'standard', lvl: 8, atk: 2800, def: 2600, base: 'legend',
    effect: 'Wenn diese Karte beschworen wird: Zerstöre alle Karten mit 3 Sternen oder weniger.' },
  { id: 'schwanenjungfrau', name: 'Schwanenjungfrau', theme: 'Musik', set: 'premium', lvl: 4, atk: 1300, def: 1700, base: 'haeufig',
    effect: 'Einmal pro Zug: Negiere einen Angriff auf eine eigene Karte mit 4 Sternen oder weniger.' },
  { id: 'cybersamurai', name: 'Cyber-Samurai', theme: 'Technik', set: 'standard', lvl: 7, atk: 2500, def: 2000, base: 'selten',
    effect: 'Diese Karte kann zweimal pro Zug angreifen, greift dann aber nur Karten an.' },
  { id: 'panthergoettin', name: 'Panthergöttin', theme: 'Geografie', set: 'premium', lvl: 8, atk: 2900, def: 2500, base: 'legend',
    effect: 'Solange diese Karte liegt, kann der Gegner keine Effekte von Karten mit 6 Sternen oder weniger nutzen.' },
  { id: 'schneemagier', name: 'Schneemann-Magier', theme: 'Wissen', set: 'standard', lvl: 3, atk: 900, def: 1200, base: 'haeufig',
    effect: 'Wenn diese Karte zerstört wird: Der Gegner muss 1 Karte ablegen.' },
  { id: 'rennwagen', name: 'Zielflaggen-Bolide', theme: 'Sport', set: 'premium', lvl: 5, atk: 2000, def: 1000, base: 'selten',
    effect: 'Wenn diese Karte als Erste in einem Zug angreift: Sie erhält 500 ATK.' },
  { id: 'pharao', name: 'Pharaonen-König', theme: 'Geschichte', set: 'standard', lvl: 9, atk: 3100, def: 2900, base: 'legend',
    effect: 'Einmal pro Duell: Beschwöre 2 Karten mit bis zu 4 Sternen aus deinem Friedhof.' },
  { id: 'riffwaechter', name: 'Riff-Wächter', theme: 'Geografie', set: 'standard', lvl: 6, atk: 2000, def: 2500, base: 'selten',
    effect: 'Solange diese Karte liegt, erleiden eigene Karten 300 weniger Kampfschaden.' },
  { id: 'bluetenpriesterin', name: 'Blütenpriesterin', theme: 'Geschichte', set: 'premium', lvl: 5, atk: 1700, def: 1900, base: 'selten',
    effect: 'Einmal pro Zug: Nimm 1 eigene Karte mit bis zu 4 Sternen auf die Hand zurück.' },
  { id: 'blitzadler', name: 'Blitzadler', theme: 'Weltall', set: 'standard', lvl: 6, atk: 2300, def: 1600, base: 'selten',
    effect: 'Wenn diese Karte angreift: Der Gegner kann in diesem Zug nicht heilen.' },
  { id: 'uhrmachergnom', name: 'Uhrmacher-Gnom', theme: 'Technik', set: 'premium', lvl: 3, atk: 1000, def: 1000, base: 'haeufig',
    effect: 'Einmal pro Zug: Sieh dir die oberste Karte deines Decks an und lege sie unter das Deck.' },
  { id: 'mondgoettin', name: 'Mondgöttin', theme: 'Weltall', set: 'standard', lvl: 8, atk: 2800, def: 2700, base: 'legend',
    effect: 'Solange diese Karte liegt, erhalten alle eigenen Karten 400 DEF.' },
  { id: 'kriegselefant', name: 'Kriegselefant', theme: 'Geschichte', set: 'premium', lvl: 7, atk: 2600, def: 2300, base: 'selten',
    effect: 'Diese Karte kann zwei Karten gleichzeitig angreifen.' },
  { id: 'graffitigeist', name: 'Graffiti-Geist', theme: 'Film & Kultur', set: 'premium', lvl: 4, atk: 1400, def: 1300, base: 'haeufig',
    effect: 'Einmal pro Zug: Tarne 1 eigene Karte, sie kann nicht angegriffen werden.' },
  { id: 'eisdrache', name: 'Eisdrache', theme: 'Weltall', set: 'premium', lvl: 9, atk: 3100, def: 2800, base: 'legend',
    effect: 'Wenn diese Karte beschworen wird: Friere alle gegnerischen Karten für einen Zug ein.' },
  { id: 'kuechenhexe', name: 'Küchenhexe', theme: 'BookTok', set: 'standard', lvl: 3, atk: 900, def: 1300, base: 'haeufig',
    effect: 'Wenn diese Karte beschworen wird: Heile 300 Lebenspunkte für jede eigene Karte.' },
  { id: 'asteroidenschuerfer', name: 'Asteroiden-Schürfer', theme: 'Weltall', set: 'premium', lvl: 5, atk: 1800, def: 1700, base: 'selten',
    effect: 'Einmal pro Zug: Ziehe 1 Karte, wenn du in diesem Zug keine Karte beschworen hast.' },
  { id: 'pfauenritter', name: 'Pfauenritter', theme: 'Bauwerke', set: 'standard', lvl: 6, atk: 2100, def: 2200, base: 'selten',
    effect: 'Wenn diese Karte angegriffen wird: Der Angreifer verliert 500 ATK bis zum Zugende.' },
  { id: 'wasserspeier', name: 'Wasserspeier', theme: 'Bauwerke', set: 'premium', lvl: 5, atk: 1900, def: 2000, base: 'selten',
    effect: 'Diese Karte kann einmal pro Duell nicht zerstört werden.' },
  { id: 'leuchtturmnixe', name: 'Leuchtturm-Nixe', theme: 'Geografie', set: 'standard', lvl: 5, atk: 1700, def: 1900, base: 'selten',
    effect: 'Einmal pro Zug: Lenke einen Angriff auf eine andere eigene Karte um.' },
  { id: 'schleimkoenig', name: 'Schleimkönig', theme: 'Film & Kultur', set: 'premium', lvl: 4, atk: 1400, def: 1500, base: 'haeufig',
    effect: 'Wenn diese Karte zerstört wird: Beschwöre 2 Karten mit 2 Sternen aus deinem Deck.' },
  { id: 'luchador', name: 'Luchador', theme: 'Sport', set: 'standard', lvl: 5, atk: 2000, def: 1400, base: 'selten',
    effect: 'Wenn diese Karte eine Karte zerstört: Sie greift sofort noch einmal an.' },
  { id: 'lavendelfee', name: 'Lavendelfee', theme: 'Wissen', set: 'premium', lvl: 3, atk: 800, def: 1200, base: 'haeufig',
    effect: 'Solange diese Karte liegt, kostet deine erste Beschwörung pro Zug keinen Tribut.' },
  { id: 'stadttitan', name: 'Stadt-Titan', theme: 'Bauwerke', set: 'standard', lvl: 9, atk: 3200, def: 3000, base: 'legend',
    effect: 'Wenn diese Karte beschworen wird: Zerstöre 1 gegnerische Karte, egal welche.' },
  { id: 'wahrsagerin', name: 'Wahrsagerin', theme: 'BookTok', set: 'premium', lvl: 5, atk: 1600, def: 2000, base: 'selten',
    effect: 'Einmal pro Zug: Sieh dir die obersten 3 Karten des gegnerischen Decks an.' },
  { id: 'skorpiondrohne', name: 'Skorpion-Drohne', theme: 'Counter-Strike', set: 'standard', lvl: 5, atk: 1900, def: 1500, base: 'selten',
    effect: 'Wenn diese Karte angreift: Der Gegner muss 1 Karte ablegen.' },
  { id: 'winterkoenigin', name: 'Winterkönigin', theme: 'Wissen', set: 'premium', lvl: 8, atk: 2900, def: 2600, base: 'legend',
    effect: 'Solange diese Karte liegt, kann der Gegner höchstens 1 Karte pro Zug beschwören.' },
  { id: 'artillerist', name: 'Artillerist', theme: 'Call of Duty', set: 'standard', lvl: 6, atk: 2400, def: 1600, base: 'selten',
    effect: 'Einmal pro Zug: Füge einer gegnerischen Karte 600 Schaden zu, ohne anzugreifen.' },
  { id: 'sonnenloewe', name: 'Sonnenlöwe', theme: 'Geografie', set: 'premium', lvl: 8, atk: 2900, def: 2400, base: 'legend',
    effect: 'Solange diese Karte liegt, erhalten alle eigenen Karten 500 ATK, aber 200 weniger DEF.' },
  { id: 'uhrwerkengel', name: 'Uhrwerk-Engel', theme: 'Technik', set: 'standard', lvl: 9, atk: 3000, def: 3000, base: 'legend',
    effect: 'Einmal pro Duell: Setze das Feld zurück, alle Karten kehren auf die Hand zurück.' },
  { id: 'fruehlingsgeist', name: 'Frühlingsgeist', theme: 'Wissen', set: 'premium', lvl: 3, atk: 900, def: 1000, base: 'haeufig',
    effect: 'Wenn diese Karte beschworen wird: Ziehe 1 Karte, wenn du keine Karte auf dem Feld hast.' },
  { id: 'g1', name: 'Knochenschrecken', theme: 'Special', set: 'ghost', lvl: 10, atk: 3300, def: 2900, base: 'ghost',
    effect: 'Wenn diese Karte beschworen wird: Alle anderen Karten auf dem Feld verlieren 500 ATK.' },
  { id: 'g2', name: 'Phantombibliothek', theme: 'Special', set: 'ghost', lvl: 8, atk: 2600, def: 3100, base: 'ghost',
    effect: 'Einmal pro Zug: Ziehe 2 Karten und lege danach 1 Karte ab.' },
  { id: 'g3', name: 'Nebelkönigin', theme: 'Special', set: 'ghost', lvl: 9, atk: 2900, def: 3000, base: 'ghost',
    effect: 'Solange diese Karte liegt, kann der Gegner keine Effekte im eigenen Zug aktivieren.' },
  { id: 'g4', name: 'Geisterwolf', theme: 'Special', set: 'ghost', lvl: 7, atk: 2500, def: 1900, base: 'ghost',
    effect: 'Diese Karte kann nicht als Ziel gewählt werden und greift direkt an, wenn sie allein steht.' },
  { id: 'g5', name: 'Uhr ohne Zeiger', theme: 'Special', set: 'ghost', lvl: 9, atk: 2800, def: 2800, base: 'ghost',
    effect: 'Einmal pro Duell: Wiederhole deinen Zug sofort.' },
  { id: 'g6', name: 'Rauchdrache', theme: 'Special', set: 'ghost', lvl: 10, atk: 3400, def: 2600, base: 'ghost',
    effect: 'Wenn diese Karte angreift: Der Gegner kann bis zum Zugende nicht blocken.' },
  { id: 'g7', name: 'Glastänzerin', theme: 'Special', set: 'ghost', lvl: 7, atk: 2300, def: 2400, base: 'ghost',
    effect: 'Wenn diese Karte zerstört wird: Zerstöre alle Karten mit 5 Sternen oder weniger.' },
  { id: 'g8', name: 'Laternenwächter', theme: 'Special', set: 'ghost', lvl: 8, atk: 2700, def: 2700, base: 'ghost',
    effect: 'Solange diese Karte liegt, kehren zerstörte eigene Karten auf die Hand zurück statt auf den Friedhof.' },
  { id: 'g9', name: 'Nebelwal', theme: 'Special', set: 'ghost', lvl: 10, atk: 3200, def: 3200, base: 'ghost',
    effect: 'Einmal pro Duell: Nimm alle gegnerischen Karten auf die Hand zurück.' },
  { id: 'g10', name: 'Das letzte Kapitel', theme: 'Special', set: 'ghost', lvl: 9, atk: 3000, def: 2500, base: 'ghost',
    effect: 'Wenn diese Karte als letzte Karte deiner Hand beschworen wird: Sie erhält 1500 ATK.' },
  // ---------- Set Toon-Welt: 30 Karten, nur im Toon-Welt-Booster ----------
  { id: 't01', name: "Toon-Orakelmagierin", theme: 'Wissen', lvl: 8, atk: 2600, def: 2200, set: 'toon', base: 'legend',
    effect: "Wenn diese Karte beschworen wird: Schau dir die obersten 3 Karten deines Decks an und lege sie in beliebiger Reihenfolge zurück." },
  { id: 't02', name: "Toon-Sternendrache", theme: 'Weltall', lvl: 8, atk: 3000, def: 2500, set: 'toon', base: 'legend',
    effect: "Solange diese Karte liegt, können Toon-Monster mit 1500 ATK oder weniger nicht angegriffen werden." },
  { id: 't03', name: "Toon-Dinokaiser", theme: 'Geschichte', lvl: 8, atk: 2800, def: 2400, set: 'toon', base: 'legend',
    effect: "Einmal pro Zug: Wähle 1 Monster deines Gegners, es verliert 500 ATK bis zum Ende des Zuges." },
  { id: 't04', name: "Toon-Zeitmagier", theme: 'Geschichte', lvl: 7, atk: 2500, def: 2100, set: 'toon', base: 'ultra',
    effect: "Einmal pro Zug: Setze ein Monster auf dem Feld auf seine ursprünglichen Werte zurück." },
  { id: 't05', name: "Toon-Uhrwerkengelin", theme: 'Technik', lvl: 7, atk: 2400, def: 2300, set: 'toon', base: 'ultra',
    effect: "Wenn diese Karte zerstört würde, zahle 500 Lebenspunkte, um sie stattdessen zu behalten." },
  { id: 't06', name: "Toon-Schattenhexer", theme: 'Wissen', lvl: 7, atk: 2500, def: 2100, set: 'toon', base: 'ultra',
    effect: "Einmal pro Zug: Zerstöre 1 Zauberkarte deines Gegners." },
  { id: 't07', name: "Toon-Wahrsagerin", theme: 'Wissen', lvl: 6, atk: 2000, def: 1800, set: 'toon', base: 'holo',
    effect: "Rate eine Zahl von 1 bis 6 und würfle. Liegst du richtig, ziehe 2 Karten." },
  { id: 't08', name: "Toon-Blitzdrache", theme: 'Wissen', lvl: 6, atk: 2200, def: 1600, set: 'toon', base: 'holo',
    effect: "Diese Karte kann direkt angreifen, wenn du eine Toon-Karte kontrollierst." },
  { id: 't09', name: "Toon-Kristallgolem", theme: 'Geografie', lvl: 6, atk: 1900, def: 2400, set: 'toon', base: 'holo',
    effect: "Solange diese Karte in Verteidigung liegt, erhält sie 600 DEF." },
  { id: 't10', name: "Toon-Raptoren-Show", theme: 'Casino', lvl: 6, atk: 2100, def: 1700, set: 'toon', base: 'holo',
    effect: "Wenn diese Karte angreift, ziehe 1 Karte. Ist es eine Monsterkarte, erhält diese Karte 300 ATK." },
  { id: 't11', name: "Toon-Maßbandkobold", theme: 'Technik', lvl: 4, atk: 1500, def: 1200, set: 'toon', base: 'selten',
    effect: "Einmal pro Zug: Vergleiche die ATK zweier Monster. Das höhere erhält 200 ATK." },
  { id: 't12', name: "Toon-Quizeule", theme: 'Wissen', lvl: 4, atk: 1400, def: 1600, set: 'toon', base: 'selten',
    effect: "Wenn diese Karte beschworen wird: Ziehe 1 Karte, dann lege 1 Karte ab." },
  { id: 't13', name: "Toon-Harlekin", theme: 'Casino', lvl: 4, atk: 1600, def: 1300, set: 'toon', base: 'selten',
    effect: "Einmal pro Zug: Tausche die ATK und DEF dieser Karte bis zum Ende des Zuges." },
  { id: 't14', name: "Toon-Piratenkatze", theme: 'Geografie', lvl: 4, atk: 1700, def: 1100, set: 'toon', base: 'selten',
    effect: "Wenn diese Karte Kampfschaden verursacht, erhältst du 300 Lebenspunkte." },
  { id: 't15', name: "Toon-Mondhexe", theme: 'Weltall', lvl: 5, atk: 1800, def: 1400, set: 'toon', base: 'selten',
    effect: "Solange diese Karte liegt, erhalten alle Toon-Monster 200 DEF." },
  { id: 't16', name: "Toon-Pegasus", theme: 'Geschichte', lvl: 4, atk: 1600, def: 1500, set: 'toon', base: 'selten',
    effect: "Diese Karte kann in einem Zug zweimal angreifen, wenn dein Gegner keine Monster kontrolliert." },
  { id: 't17', name: "Toon-Rittermaus", theme: 'Geschichte', lvl: 3, atk: 1200, def: 1800, set: 'toon', base: 'selten',
    effect: "Diese Karte kann nicht durch Kampf zerstört werden, solange sie in Verteidigung liegt." },
  { id: 't18', name: "Toon-Croupierfuchs", theme: 'Casino', lvl: 4, atk: 1700, def: 1300, set: 'toon', base: 'selten',
    effect: "Einmal pro Zug: Wirf eine Münze. Kopf: Diese Karte erhält 500 ATK. Zahl: Sie verliert 300 ATK." },
  { id: 't19', name: "Toon-Buchwurm", theme: 'Wissen', lvl: 2, atk: 800, def: 900, set: 'toon', base: 'haeufig',
    effect: "Wenn diese Karte zerstört wird: Ziehe 1 Karte." },
  { id: 't20', name: "Toon-Tintengelehrter", theme: 'Wissen', lvl: 3, atk: 1000, def: 1100, set: 'toon', base: 'haeufig',
    effect: "Einmal pro Zug: Schau dir die oberste Karte deines Decks an." },
  { id: 't21', name: "Toon-Koboldbote", theme: 'Geografie', lvl: 3, atk: 900, def: 700, set: 'toon', base: 'haeufig',
    effect: "Wenn diese Karte beschworen wird, darfst du 1 Toon-Monster der Stufe 3 oder niedriger zusätzlich beschwören." },
  { id: 't22', name: "Toon-Kerzengeist", theme: 'Geschichte', lvl: 2, atk: 700, def: 1000, set: 'toon', base: 'haeufig',
    effect: "Solange diese Karte liegt, erhalten deine Toon-Monster 100 ATK." },
  { id: 't23', name: "Toon-Pilzmagier", theme: 'Geografie', lvl: 3, atk: 1100, def: 800, set: 'toon', base: 'haeufig',
    effect: "Einmal pro Zug: Eine Karte auf dem Feld verliert 200 DEF." },
  { id: 't24', name: "Toon-Triceratopsbaby", theme: 'Geschichte', lvl: 3, atk: 1000, def: 1200, set: 'toon', base: 'haeufig',
    effect: "Diese Karte erhält 300 ATK, wenn sie ein Monster in Verteidigung angreift." },
  { id: 't25', name: "Toon-Kanonenschwein", theme: 'Geografie', lvl: 3, atk: 1200, def: 600, set: 'toon', base: 'haeufig',
    effect: "Wenn diese Karte angreift, erleidet dein Gegner 200 Schaden." },
  { id: 't26', name: "Toon-Sternenhase", theme: 'Weltall', lvl: 3, atk: 900, def: 900, set: 'toon', base: 'haeufig',
    effect: "Einmal pro Zug: Diese Karte erhält 100 ATK für jedes Toon-Monster auf dem Feld." },
  { id: 't27', name: "Toon-Würfelgolem", theme: 'Casino', lvl: 3, atk: 1100, def: 1000, set: 'toon', base: 'haeufig',
    effect: "Würfle, wenn diese Karte beschworen wird. Sie erhält 100 ATK je Augenzahl." },
  { id: 't28', name: "Toon-Schatzmimic", theme: 'Casino', lvl: 3, atk: 1300, def: 700, set: 'toon', base: 'haeufig',
    effect: "Wenn diese Karte zerstört wird, erhältst du 500 Lebenspunkte." },
  { id: 't29', name: "Toon-Gargoylewächter", theme: 'Bauwerke', lvl: 3, atk: 1000, def: 1300, set: 'toon', base: 'haeufig',
    effect: "Solange diese Karte liegt, kann dein Gegner keine Karten von deinem Feld zurück auf die Hand schicken." },
  { id: 't30', name: "Toon-Kürbisritter", theme: 'Geschichte', lvl: 3, atk: 1200, def: 900, set: 'toon', base: 'haeufig',
    effect: "Wenn diese Karte ein Monster zerstört, erhält sie 200 ATK." },
];
// Welche Varianten es je Karte gibt
const VARIANTS = {
  kobold: ["haeufig"],
  falke: ["haeufig"],
  golem: ["selten", "holo", "ultra"],
  orakel: ["selten", "holo", "ultra"],
  drache: ["legend", "ultra", "ext"],
  schmied: ["legend", "ultra", "ext"],
  eisfee: ["haeufig"],
  einhorn: ["selten", "holo", "ultra"],
  sternpanther: ["selten", "holo", "ultra"],
  domgolem: ["legend", "ultra", "ext"],
  astroritter: ["selten", "holo", "ultra"],
  inselschildkroete: ["selten", "holo", "ultra"],
  schildmaid: ["selten", "holo", "ultra"],
  gepardwagen: ["selten", "holo", "ultra"],
  notentaenzerin: ["haeufig"],
  nachtoperator: ["selten", "holo", "ultra"],
  entschaerfer: ["selten", "holo", "ultra"],
  buechermagierin: ["selten", "holo", "ultra"],
  blaetterphoenix: ["legend", "ultra", "ext"],
  meerkoenigin: ["selten", "holo", "ultra"],
  uhreule: ["haeufig"],
  sphinx: ["selten", "holo", "ultra"],
  sturmriese: ["legend", "ultra", "ext"],
  gartenfee: ["haeufig"],
  fuchssamurai: ["selten", "holo", "ultra"],
  torjaeger: ["selten", "holo", "ultra"],
  kristallhirsch: ["selten", "holo", "ultra"],
  luftschifferin: ["selten", "holo", "ultra"],
  cyberkatze: ["haeufig"],
  goldskarabaeus: ["selten", "holo", "ultra"],
  leuchtturm: ["selten", "holo", "ultra"],
  blumenfee: ["selten", "holo", "ultra"],
  schneeleopard: ["selten", "holo", "ultra"],
  kolibri: ["haeufig"],
  piratin: ["selten", "holo", "ultra"],
  lavatitan: ["legend", "ultra", "ext"],
  frosttaenzerin: ["haeufig"],
  rallyefahrer: ["selten", "holo", "ultra"],
  gelehrter: ["selten", "holo", "ultra"],
  mondhase: ["haeufig"],
  donnervogel: ["legend", "ultra", "ext"],
  vampirin: ["selten", "holo", "ultra"],
  himmelwal: ["legend", "ultra", "ext"],
  sonnenblume: ["haeufig"],
  tafelritter: ["selten", "holo", "ultra"],
  kochbot: ["haeufig"],
  quallenhexe: ["selten", "holo", "ultra"],
  brueckentroll: ["selten", "holo", "ultra"],
  eiskunst: ["haeufig"],
  wuestennomade: ["selten", "holo", "ultra"],
  zuckerhexe: ["selten", "holo", "ultra"],
  kampfmech: ["legend", "ultra", "ext"],
  waldruidin: ["selten", "holo", "ultra"],
  greif: ["selten", "holo", "ultra"],
  laternenfuchs: ["selten", "holo", "ultra"],
  luftpiratin: ["selten", "holo", "ultra"],
  kristallspinne: ["haeufig"],
  dunker: ["selten", "holo", "ultra"],
  teegeist: ["haeufig"],
  nashornpanzer: ["selten", "holo", "ultra"],
  rosenritterin: ["selten", "holo", "ultra"],
  lavasalamander: ["haeufig"],
  plattenmagier: ["selten", "holo", "ultra"],
  polarwolf: ["selten", "holo", "ultra"],
  porzellanpuppe: ["selten", "holo", "ultra"],
  buecherdrache: ["legend", "ultra", "ext"],
  schmiedezwerg: ["selten", "holo", "ultra"],
  schmetterling: ["selten", "holo", "ultra"],
  scharfschuetze: ["selten", "holo", "ultra"],
  magmagolem: ["legend", "ultra", "ext"],
  schwanenjungfrau: ["haeufig"],
  cybersamurai: ["selten", "holo", "ultra"],
  panthergoettin: ["legend", "ultra", "ext"],
  schneemagier: ["haeufig"],
  rennwagen: ["selten", "holo", "ultra"],
  pharao: ["legend", "ultra", "ext"],
  riffwaechter: ["selten", "holo", "ultra"],
  bluetenpriesterin: ["selten", "holo", "ultra"],
  blitzadler: ["selten", "holo", "ultra"],
  uhrmachergnom: ["haeufig"],
  mondgoettin: ["legend", "ultra", "ext"],
  kriegselefant: ["selten", "holo", "ultra"],
  graffitigeist: ["haeufig"],
  eisdrache: ["legend", "ultra", "ext"],
  kuechenhexe: ["haeufig"],
  asteroidenschuerfer: ["selten", "holo", "ultra"],
  pfauenritter: ["selten", "holo", "ultra"],
  wasserspeier: ["selten", "holo", "ultra"],
  leuchtturmnixe: ["selten", "holo", "ultra"],
  schleimkoenig: ["haeufig"],
  luchador: ["selten", "holo", "ultra"],
  lavendelfee: ["haeufig"],
  stadttitan: ["legend", "ultra", "ext"],
  wahrsagerin: ["selten", "holo", "ultra"],
  skorpiondrohne: ["selten", "holo", "ultra"],
  winterkoenigin: ["legend", "ultra", "ext"],
  artillerist: ["selten", "holo", "ultra"],
  sonnenloewe: ["legend", "ultra", "ext"],
  uhrwerkengel: ["legend", "ultra", "ext"],
  fruehlingsgeist: ["haeufig"],
  g1: ["ghost"],
  g2: ["ghost"],
  g3: ["ghost"],
  g4: ["ghost"],
  g5: ["ghost"],
  g6: ["ghost"],
  g7: ["ghost"],
  g8: ["ghost"],
  g9: ["ghost"],
  g10: ["ghost"],
  t01: ["legend", "ext"],
  t02: ["legend", "ext"],
  t03: ["legend", "ext"],
  t04: ["ultra"],
  t05: ["ultra"],
  t06: ["ultra"],
  t07: ["holo"],
  t08: ["holo"],
  t09: ["holo"],
  t10: ["holo"],
  t11: ["selten"],
  t12: ["selten"],
  t13: ["selten"],
  t14: ["selten"],
  t15: ["selten"],
  t16: ["selten"],
  t17: ["selten"],
  t18: ["selten"],
  t19: ["haeufig"],
  t20: ["haeufig"],
  t21: ["haeufig"],
  t22: ["haeufig"],
  t23: ["haeufig"],
  t24: ["haeufig"],
  t25: ["haeufig"],
  t26: ["haeufig"],
  t27: ["haeufig"],
  t28: ["haeufig"],
  t29: ["haeufig"],
  t30: ["haeufig"],
};
const VAR_NAME = { haeufig: 'Häufig', selten: 'Selten', holo: 'Holo', ultra: 'Ultra Rare', legend: 'Legendär', ext: 'Extended Art', ghost: 'Ghost Rare' };
const VAR_ORDER = ['haeufig', 'selten', 'holo', 'legend', 'ultra', 'ext', 'ghost'];

const PACKS = {
  standard: { id: 'standard', name: 'Standard-Booster', price: 300, cards: 3,
    odds: { haeufig: 0.68, selten: 0.21, legend: 0.03, holo: 0.05, ultra: 0.024, ext: 0.006 } },
  premium:  { id: 'premium',  name: 'Premium-Booster',  price: 550, cards: 3,
    odds: { haeufig: 0.45, selten: 0.31, legend: 0.05, holo: 0.11, ultra: 0.06, ext: 0.02 } },
  toon:     { id: 'toon',     name: 'Toon-Welt-Booster', price: 2000, cards: 2, isNew: true, only: 'toon',
    odds: { haeufig: 0.47, selten: 0.30, holo: 0.12, ultra: 0.07, legend: 0.035, ext: 0.005 } },
  ghost:    { id: 'ghost',    name: 'Geister-Booster',   price: 800, cards: 3, all: true,
    odds: { haeufig: 0.44, selten: 0.33, legend: 0.045, holo: 0.13, ultra: 0.049, ghost: 0.006 } },
};

const card = (id) => CARDS.find((c) => c.id === id) || null;
const has = (id, v) => !!VARIANTS[id] && VARIANTS[id].includes(v);
// Welche Karten gibt es in dieser Stufe?
function poolFor(v, set) {
  const pack = PACKS[set];
  const inSet = (c) => (c.set === 'toon' ? set === 'toon' : set === 'toon' ? false : c.set === 'ghost' ? set === 'ghost' : !set || (pack && pack.all) || c.set === set);
  if (v === 'ghost') return CARDS.filter((c) => c.base === 'ghost' && set === 'ghost').map((c) => c.id);
  if (v === 'haeufig' || v === 'selten' || v === 'legend') return CARDS.filter((c) => c.base === v && inSet(c)).map((c) => c.id);
  return CARDS.filter((c) => inSet(c) && VARIANTS[c.id] && VARIANTS[c.id].includes(v)).map((c) => c.id);
}
function rollVariant(odds, minimum) {
  const keys = Object.keys(odds);
  let r = Math.random(), acc = 0, pick = keys[0];
  for (const k of keys) { acc += odds[k]; if (r <= acc) { pick = k; break; } }
  if (minimum) {
    const rank = (x) => VAR_ORDER.indexOf(x);
    if (rank(pick) < rank(minimum)) pick = minimum;
  }
  return pick;
}
function openPack(packId) {
  const p = PACKS[packId]; if (!p) return [];
  const out = [];
  for (let i = 0; i < p.cards; i++) {
    let v = rollVariant(p.odds, i === p.cards - 1 ? 'selten' : null);
    let pool = poolFor(v, packId);
    if (!pool.length) { v = 'selten'; pool = poolFor(v, packId); }
    if (!pool.length) { v = 'haeufig'; pool = poolFor(v, packId); }
    const id = pool[Math.floor(Math.random() * pool.length)];
    out.push({ id, variant: has(id, v) ? v : VARIANTS[id][0] });
  }
  return out;
}
// Diamanten pro Match: bis 200, abhängig von Sieg und Punkten
function diamondsFor({ win, score, pointLimit, counted }) {
  if (!counted) return 0;
  // Punkte zählen direkt, längere Matches bringen deshalb spürbar mehr
  const lim = Math.max(300, Math.min(10000, pointLimit || 1000));
  const base = win ? 90 : 25;
  const cap = win ? Math.round(100 + lim / 6) : Math.round(50 + lim / 12);
  return Math.max(0, Math.min(cap, Math.round(base + Math.max(0, score) / 7)));
}
const view = () => ({ cards: CARDS, variants: VARIANTS, names: VAR_NAME, order: VAR_ORDER, packs: Object.values(PACKS) });
module.exports = { CARDS, VARIANTS, VAR_NAME, VAR_ORDER, PACKS, card, has, openPack, diamondsFor, view };
